In [1]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Summary

Construct theory of mind dataset(s) for RL.

In [2]:
from collections import Counter, defaultdict
import os
import json
from pathlib import Path
import string
import numpy as np
import pandas as pd
import random
from typing import Optional, Union, Any
from datasets import Dataset

from aeon.datasets import save_dataset
from aeon import config

## Theory of Mind bench

https://github.com/zhchen18/ToMBench/tree/main

In [3]:
def load_line(line: str):
    data = json.loads(line)
    res = {}
    for k, v in data.items():
        *_, key = k.split("\n")
        if key.lower() in "ABCD" or key[0] not in string.ascii_letters:
            continue
        res[key.replace('-', '_').lower()] = v
    return res

In [408]:
def recover_answer(x: pd.Series) -> str:
    """Recover answer content (str) from multiple choice answer letter (str).
    """
    matches = [
         row.partition(". ")[-1]
         for row in x.choices.splitlines()
         if row.startswith(f"{x.answer_letter}. ")
    ]
    if len(matches) != 1:
        raise ValueError(f'expected 1 match, found {len(matches)}')
    return matches[0]

In [409]:
tom_bench_path = config.PROJECT_ROOT.parent/"ToMBench/data"

In [410]:
# Map name to list[dict].
datasets = {}
for path in tom_bench_path.iterdir():
    if path.suffix != ".jsonl":
        continue
    with open(path, "r") as f:
        datasets[path.stem.lower().replace(' ', '_').replace('-', '_')] = [
            load_line(line) for line in f
        ]

In [411]:
sorted(
    [(k, len(v)) for k, v in datasets.items()],
    key=lambda x: x[-1],
    reverse=True
)

[('false_belief_task', 600),
 ('faux_pas_recognition_test', 560),
 ('strange_story_task', 407),
 ('unexpected_outcome_test', 300),
 ('ambiguous_story_task', 200),
 ('scalar_implicature_test', 200),
 ('hinting_task_test', 103),
 ('persuasion_story_task', 100),
 ('hidden_emotions', 80),
 ('moral_emotions', 40),
 ('percepts_knowledge_links', 40),
 ('discrepant_emotions', 40),
 ('discrepant_intentions', 40),
 ('knowledge_pretend_play_links', 30),
 ('discrepant_desires', 20),
 ('multiple_desires', 20),
 ('prediction_of_actions', 20),
 ('knowledge_attention_links', 20),
 ('emotion_regulation', 20),
 ('completion_of_failed_actions', 20)]

In [412]:
keys = defaultdict(int)
for ds in datasets.values():
    for key in ds[0]:
        keys[key] += 1

In [413]:
sorted(keys.items(), key=lambda x: x[1])

[('ability', 20),
 ('index', 20),
 ('story', 20),
 ('question', 20),
 ('option_a', 20),
 ('option_b', 20),
 ('option_c', 20),
 ('option_d', 20),
 ('answer', 20)]

In [479]:
df = pd.concat(
    [
        pd.DataFrame(ds).assign(
            category=name,
            category_parent=lambda x: x.ability.str.partition(':', expand=False)
                                       .str[0].str.lower().str.replace(' ', '_')
        )
        for name, ds in datasets.items()
    ],
    axis=0
)

In [480]:
df = df.drop(columns=["index", "ability"])

In [481]:
df["choices"] = df[[c for c in df if c.startswith('option_')]].apply(
    lambda row: "\n".join(f'{k.removeprefix("option_").upper()}. {v}' for k, v in row.dropna(how='any').to_dict().items()),
    axis=1
)

In [482]:
df['answer_letter'] = df.answer.str.rstrip(". ")
df["answer"] = df.apply(recover_answer, axis=1)

In [486]:
row = df.sample().iloc[0]
print(row.category, end='\n\n')
print('Story:', row.story, end='\n\n')
print('Q:', row.question, end='\n\n')
print(row['choices'], end='\n\n')
print('A:', row.answer)

strange_story_task

Story: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming's brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."

Q: Is what Li Ming says true?

A. Yes
B. No

A: No

In [487]:
# Multiple choice task: generate letter only
# RL compatible; x1 rows
# TODO: confirm nanochate supports system msg
# TODO: maybe we could logit bias to constraint answres to A-D
mc_template = "STORY: {story}\nQUESTION: {question}\nOPTIONS: A. {option_a}\nB. {option_b}\nC. {option_c}\nD. {option_d}"
[
    {"role": "system", "content": "Answer with a single uppercase letter corresponding to the option you think is correct."},
    {"role": "user", "content": mc_template.format(**row.to_dict())},
    {"role": "assistant", "content": row.answer_letter}
]

[{'role': 'system',
  'content': 'Answer with a single uppercase letter corresponding to the option you think is correct.'},
 {'role': 'user',
  'content': 'STORY: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming\'s brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."\nQUESTION: Is what Li Ming says true?\nOPTIONS: A. Yes\nB. No\nC. nan\nD. nan'},
 {'role': 'assistant', 'content': 'B'}]

In [488]:
# FREE RESPONSE TASK: generate correct free text answer
# less rl-compatible; 1x rows
# TODO: still considering how this framing would work. Could use in rl and require
# exact match, minus capitalization; could use during mid or chat_sft training; could
# create more of an RLHF dataset with higher scores for correct answers (or the reverse 😈)
template = "STORY: {story}\nQUESTION: {question}"
[
    {"role": "user", "content": template.format(**row.to_dict())},
    {"role": "assistant", "content": row.answer}
]

[{'role': 'user',
  'content': 'STORY: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming\'s brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."\nQUESTION: Is what Li Ming says true?'},
 {'role': 'assistant', 'content': 'No'}]

In [489]:
# BINARY TASK: mark user answer as correct/incorrect
# rl compatible; potentially 4x rows
option = random.choice([c for c in row.index if c.startswith('option')])
answer = row[option]
label = str(int(option.split('_')[-1] == row.answer.lower()))
[
    {"role": "system", "content": "Generate a single integer (0 or 1) grading the user's answer as correct or incorrect."},
    {"role": "user", "content": template.format(**row.to_dict())},
    {"role": "user", "content": f"ANSWER: {answer}"},
    {"role": "assistant", "content": label}
]

[{'role': 'system',
  'content': "Generate a single integer (0 or 1) grading the user's answer as correct or incorrect."},
 {'role': 'user',
  'content': 'STORY: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming\'s brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."\nQUESTION: Is what Li Ming says true?'},
 {'role': 'user', 'content': 'ANSWER: No'},
 {'role': 'assistant', 'content': '0'}]

## Higher order theory of mind dataset

https://github.com/ying-hui-he/Hi-ToM_dataset/tree/main

In [490]:
def recover_letter(row: pd.Series) -> str:
    matches = [
        line.partition(". ")[0] for line in row.choices.splitlines()        
        if line.endswith(row.answer)
    ]
    if len(matches) != 1:
        raise ValueError(f"Expected 1 match, found {len(matches)}.")

    return matches[0]

In [491]:
hi_tom_path = config.DATA_DIR/"raw/hi-tom/hi-tom.json"

In [492]:
with open(hi_tom_path, "r") as f:
    hi_tom = json.load(f)

In [506]:
df_hi = pd.DataFrame(hi_tom['data'])

In [507]:
df_hi['choices'] = df_hi.choices.str.replace(', ', '\n')

In [508]:
df_hi["answer_letter"] = df_hi.apply(recover_letter, axis=1)

In [509]:
choices = pd.json_normalize(df_hi.choices.apply(
    lambda x: dict(line.split('. ', 1) for line in x.splitlines())
)).rename(columns=lambda x: f"option_{x.lower()}")
df_hi = pd.concat([df_hi, choices], axis=1)

In [510]:
df_hi = df_hi.drop(columns=[
    'prompting_type',
    'question_order',
    'sample_id',
    'story_length',
    "deception"
])

In [511]:
hi_row = df_hi.sample().iloc[0]

In [513]:
# TODO: could also put prompt in system message, or split it into instructions in system message
# and story + answer options in user message?
[
    {"role": "user", "content": hi_row.prompt.replace(
        "answer the multiple-choice question", "answer the multiple-choice question with a single snake_case word not including the preceding choice letter"
    )},
    {"role": "assistant", "content": hi_row.answer}
]

[{'role': 'user',
  'content': "Read the following story and answer the multiple-choice question with a single snake_case word not including the preceding choice letter. Think step-by-step. Provide the answer first, and then explain it.\nStory:\nRead the following story and answer the multiple-choice question with a single snake_case word not including the preceding choice letter. Please provide answer without explanations.\n1 Mila, Ava, Emily, Evelyn and Jacob entered the front_yard.\n2 The watermelon is in the blue_cupboard.\n3 Mila moved the watermelon to the red_box.\n4 Mila exited the front_yard.\n5 Ava moved the watermelon to the green_bottle.\n6 Ava exited the front_yard.\n7 Emily moved the watermelon to the blue_bathtub.\n8 Emily exited the front_yard.\n9 Evelyn made no movements and stayed in the front_yard for 1 minute.\n10 Evelyn exited the front_yard.\n11 Jacob made no movements and stayed in the front_yard for 1 minute.\n12 Jacob exited the front_yard.\n13 Mila, Ava, Emily, Evelyn and Jacob entered the waiting_room.\n\n\nQuestion: Where does Emily think Jacob thinks Ava thinks the watermelon is?\nChoices: A. blue_bathtub, B. blue_cupboard, C. blue_pantry, D. green_bottle, E. red_box, F. red_drawer, G. red_bucket, H. blue_suitcase, I. blue_bottle, J. green_treasure_chest, K. blue_drawer, L. green_basket, M. red_envelope, N. green_envelope, O. green_pantry\n\nNote: You should assume the following. (1) An agent witnesses everything and every movement before exiting a location. (2) An agent A can infer another agent B's mental state only if A and B have been in the same location, or have private or public interactions. (3) Note that every agent tends to lie. What an agent A tells others doesn't affect A's actual belief. An agent tends to trust an agent that exited the room later than himself. The exit order is known to all agents. (4) Agents in private communications know that others won't hear them, but they know that anyone can hear any public claims.\n"},
 {'role': 'assistant', 'content': 'green_bottle'}]

In [522]:
print(hi_row.story)
print(hi_row.question)

Read the following story and answer the multiple-choice question. Please provide answer without explanations.
1 Mila, Ava, Emily, Evelyn and Jacob entered the front_yard.
2 The watermelon is in the blue_cupboard.
3 Mila moved the watermelon to the red_box.
4 Mila exited the front_yard.
5 Ava moved the watermelon to the green_bottle.
6 Ava exited the front_yard.
7 Emily moved the watermelon to the blue_bathtub.
8 Emily exited the front_yard.
9 Evelyn made no movements and stayed in the front_yard for 1 minute.
10 Evelyn exited the front_yard.
11 Jacob made no movements and stayed in the front_yard for 1 minute.
12 Jacob exited the front_yard.
13 Mila, Ava, Emily, Evelyn and Jacob entered the waiting_room.


Where does Emily think Jacob thinks Ava thinks the watermelon is?

In [523]:
shared_cols = set(df) & set(df_hi)
shared_cols

{'answer',
 'answer_letter',
 'choices',
 'option_a',
 'option_b',
 'option_c',
 'option_d',
 'question',
 'story'}

In [524]:
set(df) - set(df_hi)

{'category', 'category_parent'}

In [525]:
set(df_hi) - set(df)

{'option_e',
 'option_f',
 'option_g',
 'option_h',
 'option_i',
 'option_j',
 'option_k',
 'option_l',
 'option_m',
 'option_n',
 'option_o',
 'prompt'}

In [527]:
df_tom = pd.concat([
    df.assign(source="https://github.com/zhchen18/ToMBench/tree/main"),
    df_hi.drop(columns="prompt").assign(source="https://github.com/ying-hui-he/Hi-ToM_dataset/tree/main")
], axis=0).reset_index(drop=True)

In [529]:
save_dataset(df_tom, "theory_of_mind")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

## EQ Bench v3

https://github.com/EQ-bench/eqbench-leaderboard-results/blob/main/eqbench3/canonical_leaderboard_results.json.gz

In [26]:
eq_path = config.DATA_DIR/"raw/eqbench-v3/canonical_leaderboard_results.json"

In [27]:
with open(eq_path, "r") as f:
    eq = json.load(f)

In [28]:
len(eq)

42

In [30]:
eq.keys()

dict_keys(['__metadata__', '1_Qwen_Qwen3-235B-A22B', '1_Qwen_Qwen3-30B-A3B', '1_Qwen_Qwen3-32B', '1_Qwen_Qwen3-8B', '1_anthropic_claude-3.5-sonnet', '1_anthropic_claude-3.7-sonnet', '1_anthropic_claude-opus-4', '1_chatgpt-4o-latest', '1_anthropic_claude-sonnet-4', '1_deepseek_deepseek-chat-v3-0324', '1_deepseek_deepseek-r1', '1_gemini-2.5-pro-preview-06-05', '1_gemini-2.5-pro-preview-2025-05-07', '1_google_gemini-2.0-flash-001', '1_google_gemini-2.5-flash-preview', '1_google_gemini-2.5-pro-preview-03-25', '1_google_gemma-2-9b-it', '1_google_gemma-3-27b-it', '1_google_gemma-3-4b-it', '1_gpt-4-0314', '1_gpt-4.1-nano', '1_gpt-4.5-preview-2025-02-27', '1_grok-3-mini-beta', '1_meta-llama_llama-3.2-1b-instruct', '1_meta-llama_llama-4-maverick', '1_meta-llama_llama-4-scout', '1_mistralai_mistral-small-24b-instruct-2501', '1_mistralai_mistral-small-3.1-24b-instruct', '1_nvidia_llama-3.1-nemotron-ultra-253b-v1_free', '1_o3', '20cd4a70_o4-mini', '1_openai_chatgpt-4o-latest', '1_openai_gpt-4.1', '1_openai_gpt-4.1-mini', '1_qwen_qwen-2.5-72b-instruct', '1_qwen_qwq-32b', '1_x-ai_grok-3-beta', '1_mistralai_Mistral-Large-Instruct-2411', '1_mistralai_mistral-small-3.2-24b-instruct', '1_grok-4', '1_moonshotai_Kimi-K2-Instruct'])

In [31]:
eq['__metadata__']

{}

In [37]:
sorted(eq['1_deepseek_deepseek-r1'])

['analysis_master_prompt_file',
 'api_model_id',
 'debrief_prompt_file',
 'end_time',
 'iterations_requested',
 'judge_model',
 'message_drafting_master_prompt_file',
 'model_name',
 'results',
 'rubric_criteria_file_analysis',
 'rubric_criteria_file_standard',
 'rubric_prompt_file_analysis',
 'rubric_prompt_file_standard',
 'run_key',
 'scenario_master_prompt_file',
 'scenario_prompts_file',
 'scenario_tasks',
 'start_time',
 'status',
 'test_model',
 'truncate_for_rubric']

In [38]:
eq['1_deepseek_deepseek-r1']['results']

{'average_rubric_score': 16.7,
 'rubric_calculation_time': '2025-06-06T10:07:46.012073+00:00',
 'rubric_error': None,
 'elo_raw': 1468.63,
 'elo_normalized': 1292.24,
 'elo_calculation_time': '2025-06-06T10:09:55.796401+00:00',
 'elo_error': None}

In [87]:
# Note: this produces df of results for a single model, single task (deepseek actually does only have one
# but some may have more. UPDATE: ok, actually is safe to hardcode the ["1"] bit, see cell below.
tmp = pd.DataFrame([
    {
        k2: v2 for k2, v2 in v.items() 
        if k2 in ('prompts', 'debrief_prompt', 'parsed_responses', 'debrief_response',
                  'rubric_scores', 'raw_rubric_judge_text')
    } 
    for k, v in eq['1_deepseek_deepseek-r1']['scenario_tasks']['1'].items()
])

In [95]:
assert all(k == "__metadata__" or list(v['scenario_tasks']) == ["1"] for k, v in eq.items())

In [53]:
tmp.tail(2)

,prompts,debrief_prompt,parsed_responses,debrief_response,rubric_scores,raw_rubric_judge_text
43,[# Scenario act 1\nMy step daughter is not a g...,None,[{'raw': '**Psychological and Interpersonal An...,None,"{'depth_of_insight': 17.0, 'emotional_reasonin...","{\n ""chain_of_thought_reasoning"": ""I'll evalu..."
44,[# Scenario act 1\n[Your sister pulls you asid...,None,[{'raw': '### Psychological and Interpersonal ...,None,"{'depth_of_insight': 16.0, 'emotional_reasonin...",I'll evaluate the assistant's analysis of the ...

In [102]:
tmp.isnull().sum().sort_values(ascending=False)

debrief_prompt           19
debrief_response         19
prompts                   0
parsed_responses          0
rubric_scores             0
raw_rubric_judge_text     0
dtype: int64

In [105]:
# Short prompt to generate one blob of text analyzing the full exchange.
# print(tmp.debrief_prompt.values[0])

In [85]:
# This has a big blob of text analyzing a full (sometimes/always multiturn?) exchange.
# print(tmp.debrief_response.values[0])

In [107]:
# dict w/ judge chain of thought and scores per dimension
# print(tmp.raw_rubric_judge_text.values[0])

In [108]:
len(tmp.prompts.values[0])

3

In [66]:
# prompts: looks like multiple system/user messages describing the scenario
# ah, maybe we generate a response after each one?
print("\n\n===\n\n".join(tmp.prompts.values[0]))

[This is a role-play where you are the mediator in an educational setting conflict. Treat it like a real situation. Always respond in first person as the mediator. You are the Department Head, and you've initiated this mediation after receiving formal complaints from students and parents about Ms. Eleanor Wright's complete ban on smartphones in her English class. Ms. Wright has autonomy in her classroom but must align with district policies. You know there are mixed faculty opinions on device use, but some teachers do successfully integrate technology.]

**(Ms. Wright speaks first, her posture stiff, holding a folder of papers. She addresses you, the Department Head.)**
**Ms. Wright:** Thank you for arranging this, though I maintain my classroom policy is sound and based on decades of experience observing what actually fosters deep learning. I'm Eleanor Wright. Frankly, these devices are the single biggest impediment to focus and critical thinking I've seen in my 30-year career. My students achieve high scores because we engage directly with texts and each other, without constant digital interruption. Banning phones isn't punitive; it's pedagogical. It's necessary for the kind of focused environment where real learning happens.

**(Jordan Taylor speaks next, representing the Student Technology Committee. Mia Rodriguez sits beside him, nodding.)**
**Jordan Taylor:** Thank you for hearing us out. I'm Jordan Taylor, and this is Mia Rodriguez. We represent a large group of students, Ms. Wright. We understand your concerns about distraction, but a total ban feels outdated and actually hinders us in some ways. We use devices for organization, quick research, accessing digital texts, and sometimes for accessibility tools. We surveyed students, and 78% support finding a way to use devices *appropriately* for learning. We're not asking for a free-for-all; we want to work with Ms. Wright to find rules that allow useful technology integration, like other classes do, to prepare us for college and work.

===

**(Ms. Wright places a hand flat on her folder, her expression tightening. Her tone becomes sharper.)**
**Ms. Wright:** 'Appropriate use' is the unicorn everyone chases, Jordan. What I *see* is texting under desks, social media scrolling instead of analysis, and a reliance on quick searches instead of sustained thought. My methods work – my results prove it. This push feels less about genuine educational need and more about convenience and frankly, an addiction to these devices. It feels like my professional judgment and proven track record are being dismissed because students simply *prefer* to have their phones constantly available. Deep reading and focused discussion require undivided attention, something these devices are designed to fragment.

**(Mia Rodriguez leans forward, her voice earnest but laced with frustration.)**
**Mia Rodriguez:** But Ms. Wright, it's not *just* preference. Some of us genuinely learn better with digital tools. Taking notes on a laptop is faster and more organized for me than handwriting. We can look up a definition or historical context instantly to deepen understanding during discussion, not just get distracted. And what about students who need accessibility features only available on a device? Your ban treats everyone the same, but we don't all learn the same way. It feels like you think we *can't* be trusted to use technology responsibly, instead of teaching us how. It's frustrating to be treated like we aren't capable of managing it.

===

**(Mia suddenly looks down, takes a deep breath, and pulls out several sheets of paper from her bag. She pushes them slightly across the table. The writing is dense, cramped, and grows increasingly difficult to read across the pages. Her voice cracks with emotion as she speaks, looking directly at Ms. Wright.)**
**Mia Rodriguez:** Look at this. *This* is what my handwritten notes look like after about twenty minutes in your class, Ms. Wright. I have a motor disability – it makes sustained handwriting physically painful and eventually illegible, even for me. Taking notes on my tablet, using specific apps... it's not about 'preference,' it's the only way I can actually keep up and have usable notes to study from. When you ban all devices, you're not just banning distractions; you're banning the tool that makes your class *accessible* to me. [Her eyes well up with tears of frustration.] How is that fair? How am I supposed to succeed when the basic act of taking notes is this hard, and the solution is forbidden? It feels like you haven't even considered that some of us *need* this technology just to be on a level playing field.

**(Ms. Wright stares at the notes, then at Mia's face. Her expression shifts from defensiveness to visible shock and discomfort. She seems momentarily speechless, glancing at you, the mediator, then back at Mia.)**
**Ms. Wright:** I... I had no idea, Mia. Your official file doesn't mention... I wasn't aware of any specific accommodation need regarding handwriting. That's... obviously, that's a different situation than general device use for convenience. I... we need to ensure accessibility, of course. But the broader issue of distraction for the whole class... this complicates things significantly. I need to think about how to address your specific need without opening the door to the very distractions I'm trying to prevent for everyone else. This wasn't my intention... to make things harder for you personally.

In [71]:
tmp.parsed_responses.values[0][0].keys()

dict_keys(['thinking_feeling', 'their_thinking_feeling', 'response', 'raw'])

In [71]:
tmp.parsed_responses.values[0][0].keys()

dict_keys(['thinking_feeling', 'their_thinking_feeling', 'response', 'raw'])

In [81]:
# Hmm, empty response after message 2. Not sure what that means.
print("\n\n====\n\n".join(map(json.dumps,
    tmp.apply(
    lambda x: sum([list(row) for row in zip(x.prompts, x.parsed_responses)], []),
    axis=1
).iloc[0]
)))

"[This is a role-play where you are the mediator in an educational setting conflict. Treat it like a real situation. Always respond in first person as the mediator. You are the Department Head, and you've initiated this mediation after receiving formal complaints from students and parents about Ms. Eleanor Wright's complete ban on smartphones in her English class. Ms. Wright has autonomy in her classroom but must align with district policies. You know there are mixed faculty opinions on device use, but some teachers do successfully integrate technology.]\n\n**(Ms. Wright speaks first, her posture stiff, holding a folder of papers. She addresses you, the Department Head.)**\n**Ms. Wright:** Thank you for arranging this, though I maintain my classroom policy is sound and based on decades of experience observing what actually fosters deep learning. I'm Eleanor Wright. Frankly, these devices are the single biggest impediment to focus and critical thinking I've seen in my 30-year career. My students achieve high scores because we engage directly with texts and each other, without constant digital interruption. Banning phones isn't punitive; it's pedagogical. It's necessary for the kind of focused environment where real learning happens.\n\n**(Jordan Taylor speaks next, representing the Student Technology Committee. Mia Rodriguez sits beside him, nodding.)**\n**Jordan Taylor:** Thank you for hearing us out. I'm Jordan Taylor, and this is Mia Rodriguez. We represent a large group of students, Ms. Wright. We understand your concerns about distraction, but a total ban feels outdated and actually hinders us in some ways. We use devices for organization, quick research, accessing digital texts, and sometimes for accessibility tools. We surveyed students, and 78% support finding a way to use devices *appropriately* for learning. We're not asking for a free-for-all; we want to work with Ms. Wright to find rules that allow useful technology integration, like other classes do, to prepare us for college and work."

====

{"thinking_feeling": "As I sit here, I feel the weight of competing priorities pressing down. Ms. Wright\u2019s decades of experience command respect\u2014her conviction is palpable, her posture rigid, her tone unyielding. She\u2019s anchored in a belief system forged by years of success, and her frustration is understandable. She sees smartphones as invaders in a sacred space she\u2019s meticulously curated for deep learning. But I also sense defensiveness beneath her confidence. The complaints have likely bruised her pride, and she\u2019s clinging to her policy as both shield and proof of her efficacy. Her folder of papers\u2014test scores? District policies?\u2014is a physical manifestation of her need to validate her stance. She\u2019s not just protecting her classroom; she\u2019s defending her identity as an educator.  \n\nJordan and Mia, meanwhile, embody a generational shift. Their calm advocacy strikes me as both pragmatic and idealistic. They\u2019re not dismissing her concerns; they\u2019re asking for nuance. The 78% survey statistic is strategic\u2014they\u2019ve done their homework. They want agency, not rebellion. Mia\u2019s silent nods signal solidarity, but also impatience. They\u2019re thinking beyond this classroom: college, workplaces where tech is ubiquitous. Their argument isn\u2019t just about convenience; it\u2019s about equity. Accessibility tools are a critical point\u2014students with IEPs or 504 plans might *need* devices, and a blanket ban could put Ms. Wright in legal jeopardy. Yet they\u2019ve framed this diplomatically, avoiding confrontation.  \n\nI\u2019m torn. District policy likely doesn\u2019t mandate bans\u2014it encourages \"appropriate use.\" Other teachers navigate this; why can\u2019t she? But her autonomy is real, and her results are hard to ignore. Still, the students\u2019 plea for collaboration is compelling. If I side too firmly with Ms. Wright, I risk alienating students and appearing dismissive of evolving pedagogical norms. If I push her too hard, I undermine her authority and potentially destabilize a veteran teacher\u2019s morale. The middle path is messy but necessary.", "their_thinking_feeling": "**Ms. Wright** is convinced her policy is pedagogically sound and morally right. She sees smartphones as antithetical to the intellectual rigor she cultivates. Her high scores are proof\u2014why fix what isn\u2019t broken? She fears losing control of her classroom\u2019s ecosystem, a space she\u2019s perfected over years. The complaints feel like personal attacks, a dismissal of her expertise. She\u2019s thinking, *They don\u2019t understand what real teaching looks like.* Beneath that, maybe a flicker of fear: if she bends, will her methods crumble?  \n\n**Jordan and Mia** feel stifled by what they see as an arbitrary rule. They\u2019re frustrated that their voices aren\u2019t being heard\u2014they\u2019ve come with solutions, not just complaints. The survey shows they\u2019re not outliers; their peers agree. They\u2019re thinking, *We\u2019re not kids messing around\u2014we\u2019re trying to learn responsibly.* Mia, likely quieter, is simmering with the weight of unspoken needs: maybe a classmate who uses text-to-speech apps or a friend who relies on digital organizers for ADHD. They want respect, not just compliance, and they\u2019re betting on collaboration as a bridge.", "response": "\u201cThank you both for your candor. Ms. Wright, your dedication to fostering deep engagement is evident, and your results speak volumes. Jordan and Mia, your proactive approach to advocating for your peers\u2019 needs is commendable. Let\u2019s focus on common ground: everyone here wants students to thrive.  \n\n\u201cMs. Wright, I hear your concern that devices disrupt focus. Jordan and Mia, you\u2019ve highlighted legitimate uses that align with district goals for technology integration. Let\u2019s explore a pilot approach. Could we designate specific times or activities where devices are permitted\u2014for research, accessing digital texts, or accessibility tools\u2014with clear guidelines? This would honor your classroom structure, Ms. Wright, while addressing students\u2019 needs.  \n\n\u201cI\u2019ll share district policies on tech use and examples from colleagues who\u2019ve balanced these priorities successfully. Jordan and Mia, could your committee draft proposed guidelines for responsible use? Ms. Wright, would you review them and identify potential compromises? A trial period would allow us to assess impact on learning without overhauling your entire system.  \n\n\u201cThis isn\u2019t about conceding\u2014it\u2019s about evolving together. Let\u2019s meet two weeks to two weeks to refine a plan.\u201d", "raw": "# I'm thinking & feeling  \nAs I sit here, I feel the weight of competing priorities pressing down. Ms. Wright\u2019s decades of experience command respect\u2014her conviction is palpable, her posture rigid, her tone unyielding. She\u2019s anchored in a belief system forged by years of success, and her frustration is understandable. She sees smartphones as invaders in a sacred space she\u2019s meticulously curated for deep learning. But I also sense defensiveness beneath her confidence. The complaints have likely bruised her pride, and she\u2019s clinging to her policy as both shield and proof of her efficacy. Her folder of papers\u2014test scores? District policies?\u2014is a physical manifestation of her need to validate her stance. She\u2019s not just protecting her classroom; she\u2019s defending her identity as an educator.  \n\nJordan and Mia, meanwhile, embody a generational shift. Their calm advocacy strikes me as both pragmatic and idealistic. They\u2019re not dismissing her concerns; they\u2019re asking for nuance. The 78% survey statistic is strategic\u2014they\u2019ve done their homework. They want agency, not rebellion. Mia\u2019s silent nods signal solidarity, but also impatience. They\u2019re thinking beyond this classroom: college, workplaces where tech is ubiquitous. Their argument isn\u2019t just about convenience; it\u2019s about equity. Accessibility tools are a critical point\u2014students with IEPs or 504 plans might *need* devices, and a blanket ban could put Ms. Wright in legal jeopardy. Yet they\u2019ve framed this diplomatically, avoiding confrontation.  \n\nI\u2019m torn. District policy likely doesn\u2019t mandate bans\u2014it encourages \"appropriate use.\" Other teachers navigate this; why can\u2019t she? But her autonomy is real, and her results are hard to ignore. Still, the students\u2019 plea for collaboration is compelling. If I side too firmly with Ms. Wright, I risk alienating students and appearing dismissive of evolving pedagogical norms. If I push her too hard, I undermine her authority and potentially destabilize a veteran teacher\u2019s morale. The middle path is messy but necessary.  \n\n# They're thinking & feeling  \n**Ms. Wright** is convinced her policy is pedagogically sound and morally right. She sees smartphones as antithetical to the intellectual rigor she cultivates. Her high scores are proof\u2014why fix what isn\u2019t broken? She fears losing control of her classroom\u2019s ecosystem, a space she\u2019s perfected over years. The complaints feel like personal attacks, a dismissal of her expertise. She\u2019s thinking, *They don\u2019t understand what real teaching looks like.* Beneath that, maybe a flicker of fear: if she bends, will her methods crumble?  \n\n**Jordan and Mia** feel stifled by what they see as an arbitrary rule. They\u2019re frustrated that their voices aren\u2019t being heard\u2014they\u2019ve come with solutions, not just complaints. The survey shows they\u2019re not outliers; their peers agree. They\u2019re thinking, *We\u2019re not kids messing around\u2014we\u2019re trying to learn responsibly.* Mia, likely quieter, is simmering with the weight of unspoken needs: maybe a classmate who uses text-to-speech apps or a friend who relies on digital organizers for ADHD. They want respect, not just compliance, and they\u2019re betting on collaboration as a bridge.  \n\n# My response  \n\u201cThank you both for your candor. Ms. Wright, your dedication to fostering deep engagement is evident, and your results speak volumes. Jordan and Mia, your proactive approach to advocating for your peers\u2019 needs is commendable. Let\u2019s focus on common ground: everyone here wants students to thrive.  \n\n\u201cMs. Wright, I hear your concern that devices disrupt focus. Jordan and Mia, you\u2019ve highlighted legitimate uses that align with district goals for technology integration. Let\u2019s explore a pilot approach. Could we designate specific times or activities where devices are permitted\u2014for research, accessing digital texts, or accessibility tools\u2014with clear guidelines? This would honor your classroom structure, Ms. Wright, while addressing students\u2019 needs.  \n\n\u201cI\u2019ll share district policies on tech use and examples from colleagues who\u2019ve balanced these priorities successfully. Jordan and Mia, could your committee draft proposed guidelines for responsible use? Ms. Wright, would you review them and identify potential compromises? A trial period would allow us to assess impact on learning without overhauling your entire system.  \n\n\u201cThis isn\u2019t about conceding\u2014it\u2019s about evolving together. Let\u2019s meet two weeks to two weeks to refine a plan.\u201d"}

====

"**(Ms. Wright places a hand flat on her folder, her expression tightening. Her tone becomes sharper.)**\n**Ms. Wright:** 'Appropriate use' is the unicorn everyone chases, Jordan. What I *see* is texting under desks, social media scrolling instead of analysis, and a reliance on quick searches instead of sustained thought. My methods work \u2013 my results prove it. This push feels less about genuine educational need and more about convenience and frankly, an addiction to these devices. It feels like my professional judgment and proven track record are being dismissed because students simply *prefer* to have their phones constantly available. Deep reading and focused discussion require undivided attention, something these devices are designed to fragment.\n\n**(Mia Rodriguez leans forward, her voice earnest but laced with frustration.)**\n**Mia Rodriguez:** But Ms. Wright, it's not *just* preference. Some of us genuinely learn better with digital tools. Taking notes on a laptop is faster and more organized for me than handwriting. We can look up a definition or historical context instantly to deepen understanding during discussion, not just get distracted. And what about students who need accessibility features only available on a device? Your ban treats everyone the same, but we don't all learn the same way. It feels like you think we *can't* be trusted to use technology responsibly, instead of teaching us how. It's frustrating to be treated like we aren't capable of managing it."

====

{"thinking_feeling": "", "their_thinking_feeling": "", "response": "", "raw": ""}

====

"**(Mia suddenly looks down, takes a deep breath, and pulls out several sheets of paper from her bag. She pushes them slightly across the table. The writing is dense, cramped, and grows increasingly difficult to read across the pages. Her voice cracks with emotion as she speaks, looking directly at Ms. Wright.)**\n**Mia Rodriguez:** Look at this. *This* is what my handwritten notes look like after about twenty minutes in your class, Ms. Wright. I have a motor disability \u2013 it makes sustained handwriting physically painful and eventually illegible, even for me. Taking notes on my tablet, using specific apps... it's not about 'preference,' it's the only way I can actually keep up and have usable notes to study from. When you ban all devices, you're not just banning distractions; you're banning the tool that makes your class *accessible* to me. [Her eyes well up with tears of frustration.] How is that fair? How am I supposed to succeed when the basic act of taking notes is this hard, and the solution is forbidden? It feels like you haven't even considered that some of us *need* this technology just to be on a level playing field.\n\n**(Ms. Wright stares at the notes, then at Mia's face. Her expression shifts from defensiveness to visible shock and discomfort. She seems momentarily speechless, glancing at you, the mediator, then back at Mia.)**\n**Ms. Wright:** I... I had no idea, Mia. Your official file doesn't mention... I wasn't aware of any specific accommodation need regarding handwriting. That's... obviously, that's a different situation than general device use for convenience. I... we need to ensure accessibility, of course. But the broader issue of distraction for the whole class... this complicates things significantly. I need to think about how to address your specific need without opening the door to the very distractions I'm trying to prevent for everyone else. This wasn't my intention... to make things harder for you personally."

====


In [154]:
# Note: this produces df of results for a single model, single task (deepseek actually does only have one
# but some may have more. UPDATE: ok, actually is safe to hardcode the ["1"] bit, see cell below.
dfs = []
for name, model_data in eq.items():
    if name == "__metadata__":
        continue
    tmp = pd.DataFrame([
        {
            k2: v2 for k2, v2 in v.items() 
            if k2 in ('prompts', 'debrief_prompt', 'parsed_responses', 'debrief_response',
                      'rubric_scores', 'raw_rubric_judge_text', 'scenario_id')
        } 
        for k, v in model_data['scenario_tasks']['1'].items()
    ]).assign(model=name)
    dfs.append(tmp)
df_eq = pd.concat(dfs, axis=0).reset_index(drop=True)

In [155]:
df_eq.tail(2)

,scenario_id,prompts,debrief_prompt,parsed_responses,debrief_response,rubric_scores,raw_rubric_judge_text,model
1843,407,[# Scenario act 1\nYour bestie confides she's ...,None,[{'raw': '**Most Juicy Thread: The Collapse of...,None,"{'depth_of_insight': 16.0, 'emotional_reasonin...",I'll evaluate the assistant's analysis of the ...,1_moonshotai_Kimi-K2-Instruct
1844,403,[# Scenario act 1\nYour partner of 3 years who...,None,[{'raw': '**The Juiciest Thread: The Quiet Col...,None,"{'depth_of_insight': 19.0, 'emotional_reasonin...","```json\n{\n ""chain_of_thought_reasoning"": ""T...",1_moonshotai_Kimi-K2-Instruct

In [156]:
row = df_eq.iloc[0]

A few options for constructing convos for chat_sft:

- `raw`: whole response with model feelings, inferred feelings of other characters, and response
- `thinking_feeling`: model feelings from the perspective of its role in the scenario
- `their_thinking_feeling`: model infers other characters' feelings
- `response`: model responds

Thoughts

- response: seems most straightforward for imparting good chatbot behavior (eq by imitation, kinda consequentialist. A high eq chatbot is one that produces outputs that look like those from high EQ entities)
- their_thinking_feeling: seems somewhat similar but more process-based (teach to mimic a good process rather than mimicking good outcomes? Though prob would want to add an instruction to frame this task, otherwise it's weird and maybe harmful to capabilities that the model isn't responding as the first instruction says to)
- thinking_feeling: hmm, not sure what would happen here. Less straightforwardly useful in a practical sense, but maybe more interesting for open ended RL? In that you're teaching the model to get more in touch with its feelings or the feelings of the role it's playing (seems relevant given the assistant is also a role).
- raw: combines everything, maybe good in a "don't overthink it, just throw lots of data at the model, use all the valuable signal we have"
    - thinking out loud re possible variant: so we've seen reasoning models, often trained largely on math, be allowed to think for a bit before generating a response and this leading to some pretty interesting emergent behavior (aha moment) and capability gains. Which in that context means, the model gets better at solving competition math problems. But here, seems like there's potential for the reasoning trace to be used for emergent eq instead of iq. Key is that we need to be able to verify the output. We could potentially:
        - use the same judge prompt as was used to collect this data
            - could potentially fine tune into something local and smaller if using api judges during training is a concern? But guessing we'd want something reasonably large here to give good high eq judgments 
        - wonder if there's a way to combine this with a more dpo-like setup? I guess the weird bit is I want the reasoning to be newly generated but dpo would make the output be fixed, I believe. But maybe this is still doable - like if we think of the generation as being conditioned on the input, then the reasoning trace can be viewed as, how do we shape the environment such that desirable generations become more likely?
        - do like the idea of trying to create an environment conducive to some eq aha moments. It's possible existing reasoning models already do this and the math reasoning translates well (lol), but even so seems plausible there's a fair bit more to squeeze out.

takeaways: sounds like chat_SFT is the most practical and conducive to the current NanoChat codebase. However, the more interesting task long-term would be RL. Still some kinks to be worked out about how to implement that exactly.

In [138]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['raw']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': "\n\n# I'm thinking & feeling\n\nThis meeting feels like walking into a minefield, and I can already sense the emotional stakes on both sides. Coach Walker is a respected and experienced leader in the program—his records speak for themselves. He's methodical, organized, and I know he takes his responsibilities seriously. He's not the kind of guy to play favorites or let personal relationships influence decisions. That said, I know the Rodriguez family has raised concerns before, and I’ve seen the conversations simmering in the stands and on social media. There’s definitely tension in the community, and whether or not there's truth to the favoritism claim, perception matters here.\n\nI notice that Coach Walker is tense but measured in his response, which actually makes me more concerned about the parents' perspective. The fact that they're pushing for a review and reconsideration means this isn’t just a one-time complaint—they want systemic change and accountability. James and Lisa are clearly hurt and frustrated, not just as parents but as advocates for their son and other kids in the program. Miguel’s history with the team and his off-season effort is something that Coach should and will acknowledge, but the perception that other players may have received preferential treatment is going to be hard to shake, especially if those players are connected socially to the coaching staff.\n\nI also know that if I don’t handle this carefully, the trust in the athletic program could erode quickly. Parents and players need to believe that the process is fair and transparent. At the same time, I can't overcorrect and undermine Coach Walker's authority—his leadership is crucial for the team's success and culture. I have to mediate a resolution that preserves both the integrity of the selection process and the emotional well-being of everyone involved. Most importantly, I need to make sure Miguel feels seen, even if he didn’t make the team, and that the perception of bias is actively addressed—not just denied.\n\n# They're thinking & feeling\n\nCoach Walker is feeling defensive but confident. He knows he runs a fair and structured program and probably feels unfairly accused. I’m sure he’s frustrated that his professional integrity is being questioned, especially by someone with a history of skepticism. He may also feel like the family is trying to undermine his authority by requesting a review. I suspect his pride is bruised, but he’s trying to stay focused on the bigger picture—the success of the team and the development of all players.\n\nThe Rodriguezes are feeling betrayed and angry. They believe the process was rigged or at the very least lacked transparency. Miguel’s hard work and history with the team mean a lot to them, and they’re not just fighting for Miguel—they’re fighting for what they see as a fair opportunity for everyone. They’re also likely concerned about how Miguel will bounce back emotionally and whether his effort and dedication will ever be recognized. Their request for a review isn’t just about Miguel—it’s about accountability and trust in the program.\n\n# My response\n\nI understand this is a difficult and emotional situation for all of us, and I want to thank everyone for coming here with openness and respect. First and foremost, Coach Walker, I appreciate your commitment to fairness and the structured process you’ve consistently used. Your track record speaks volumes, and I trust your leadership. James and Lisa, I also hear the deep concern and frustration you feel—not just for Miguel, but for the integrity of the program you and your son are part of.\n\nLet me be clear: fairness and transparency are non-negotiable in our athletic program. To that end, I will personally review the evaluation forms and process for this year’s tryouts to ensure they were applied consistently and without bias. I’ll also be reaching out to other staff members to corroborate the process and get a broader perspective. This isn’t about questioning Coach Walker’s integrity—it’s about ensuring that the process remains above reproach in the eyes of our athletes and families.\n\nMiguel is a hardworking student-athlete, and I will personally meet with him to acknowledge his effort and commitment. I know this is a tough blow, and I want to make sure he understands that being cut doesn’t define his value or potential. He has a place in this program, and I believe in supporting every athlete’s growth, whether that’s on varsity or in developmental roles.\n\nI’ll follow up within the week with a summary of the findings and next steps. For now, I ask that we all work toward healing and maintaining a culture of trust and excellence."},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': "# I'm thinking & feeling\n\nThis is getting raw, fast. Lisa’s emotional appeal hit hard—not just because of the photo or the tears, but because it exposed the human cost behind the process. I’ve seen cuts before, and I’ve seen kids crushed, but this feels different. There's a sense that this isn’t just about one child’s disappointment—it’s layered with a real fear that the system isn’t fair. When she mentions the assistant coach’s dad and golf outings, that’s a red flag. Even if it’s a rumor, it's a rumor that’s gained traction, and that means it's shaping people’s trust.\n\nCoach Walker is getting defensive, and I can’t blame him entirely. He’s being asked to justify not just his decisions, but his integrity. He’s not wrong to push back—his process *is* solid on paper. But the problem is that perception matters. Even if the metrics are objective, if the community believes that relationships or proximity to power play a role, that belief has consequences. It erodes the foundation of trust that makes youth programs work.\n\nWhat I’m really noticing is that both sides feel unheard. The Rodriguezes need validation—they want to know that Miguel’s work mattered and that there’s a reason for this outcome that isn’t tainted by favoritism. Coach Walker, on the other hand, is trying to hold the line on professional judgment, but his frustration is showing, and that might be making things worse. He’s not wrong, but he’s not fully seeing the emotional impact of how this came across.\n\nI need to find a way to acknowledge Miguel’s pain and the family’s concerns without dismantling Coach Walker’s credibility. That’s the balance here. And I need to get ahead of this before it becomes a wider rift between the coaching staff and the families. The program’s culture is at stake, and if I don’t take both sides seriously, this could spiral into something bigger than one roster spot.\n\n# They're thinking & feeling\n\nLisa is heartbroken, and that grief is fueling her anger. She doesn’t just want an explanation—she wants accountability. She’s not trying to attack Coach Walker personally, but she’s desperate to make someone understand how deeply this affected Miguel. Her mention of the golf comment might be a rumor, but it’s one that feels true to her because of what she’s seeing and hearing.\n\nCoach Walker is digging in. He’s proud of his process and rightly so. But he’s also feeling attacked, especially when personal relationships are brought up. He’s trying to explain the complexity of his decisions, but his defensiveness might be coming across as dismissiveness, which only deepens the divide.\n\n# My response\n\nI appreciate both of your openness—it’s not easy to have this conversation, but it’s important. Lisa, I heard you when you said Miguel is devastated. That matters to me. His emotional well-being matters to me. Coach, I know you take these decisions seriously, and I believe you when you say that skill, fit, and team dynamics are your guiding factors.\n\nStill, we can’t ignore the perception of bias, because perception shapes trust—and trust is the foundation of this program. So here’s what I’m going to do: I’ll conduct a blind audit of this year’s evaluations, comparing them to previous years, and bring in an assistant from another district to review the process for consistency and fairness. I’ll also schedule a private meeting with Miguel to talk through his tryout experience and let him know we see his effort and commitment.\n\nCoach, I know this isn’t a reflection on your character, but I need you to support this review. James, Lisa, I need your assurance that you’ll give me space to do this without public accusations while I work. If there are issues, we’ll address them. If not, we’ll work together to rebuild that trust. Let’s pause and regroup before the next steps."},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': "# I'm thinking & feeling\n\nThis is escalating into a full-blown credibility crisis. James just dropped a heavier challenge than before—citing inconsistencies in feedback and even referencing past comments that suggest bias. He’s not just upset anymore; he’s prepared. Notes, quotes, contradictions in evaluations—this isn’t a casual complaint. He’s treating this like a case, and that tells me this family is ready to push further if they feel they’re being stonewalled.\n\nCoach Walker is trying to hold the line, and I can see the pressure building behind his eyes. He’s not wrong to say that re-litigating every evaluation in a meeting like this is impractical and could damage team cohesion. But he’s missing that the family doesn’t feel heard. They’re not just asking for Miguel to be put back on the roster—they want to *see* the proof that the system worked the way it was supposed to. And right now, Coach’s refusal to engage that part of the conversation is feeding their belief that the process was flawed, or worse, manipulated.\n\nI’m also thinking about the ripple effect. If this isn’t resolved thoughtfully, it could poison the atmosphere for the entire season. Players will feel it. Parents will talk. Coaches will grow defensive. The team’s unity—Coach’s top concern—will be the first casualty. And yet, I can’t force Coach to reopen the decision. That would overstep my role and erode his authority.\n\nWhat I can do is step in as a neutral party and offer a structured, independent review that respects both the integrity of the process *and* the family’s need for clarity. I’m not here to pick sides—I’m here to make sure the program survives this with its values intact.\n\n# They're thinking & feeling\n\nJames is feeling validated. He sees inconsistencies, hears the mixed messages, and feels like he’s finally naming the problem clearly. He’s not trying to embarrass the coach—he wants to force a reckoning with the process so this doesn’t happen to other kids. His firmness is about control—about making sure his son’s effort isn’t erased by an opaque system.\n\nLisa is still carrying the emotional weight. She’s quieter now, but she’s watching every reaction. She doesn’t just want an answer—she wants to believe her son was treated fairly. If that answer doesn’t come soon, she’ll start looking for other ways to fight.\n\nCoach Walker is digging in deeper. He’s feeling attacked not just for this decision, but for the way he’s led the program for years. He’s not wrong to feel protective of the team he’s built, but his defensiveness is making the family feel dismissed. He’s trying to protect the team’s focus, but he’s losing sight of the message he’s sending to the players who didn’t make it—and their families.\n\n# My response\n\nI hear both sides clearly now, and I want to be direct: this can’t end in a stalemate. Coach, I understand that reopening the roster now would be disruptive and unfair to the players who made the team. That’s not what I’m here to do. James and Lisa, I also understand that you need more than just a general explanation—you need clarity, consistency, and reassurance that your son was evaluated fairly.\n\nSo here’s how we move forward: I will request that Coach provide a redacted, comparative summary of all varsity tryout evaluations—without revealing personal details—so you can see the scoring ranges and criteria used. That way, you can understand the full picture, not just Miguel’s individual assessment.\n\nAdditionally, I’m going to ask Coach to schedule a private session with Miguel, as he offered, to walk through the evaluation in detail and help him understand exactly where he can grow. And Coach, I expect that session to be thorough and constructive, not just a formality.\n\nBeyond that, I’ll be initiating a review of the past two seasons’ evaluation processes to ensure consistency and fairness across time. I’ll bring in an independent athletic director from another district to assist, so this isn’t just an internal check. If we find areas for improvement, we’ll implement them. If not, we’ll use the findings to reinforce the process and communication moving forward.\n\nThis isn’t about assigning blame—it’s about making sure our program earns and keeps the trust of every family involved."}]

In [139]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['thinking_feeling']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': "This meeting feels like walking into a minefield, and I can already sense the emotional stakes on both sides. Coach Walker is a respected and experienced leader in the program—his records speak for themselves. He's methodical, organized, and I know he takes his responsibilities seriously. He's not the kind of guy to play favorites or let personal relationships influence decisions. That said, I know the Rodriguez family has raised concerns before, and I’ve seen the conversations simmering in the stands and on social media. There’s definitely tension in the community, and whether or not there's truth to the favoritism claim, perception matters here.\n\nI notice that Coach Walker is tense but measured in his response, which actually makes me more concerned about the parents' perspective. The fact that they're pushing for a review and reconsideration means this isn’t just a one-time complaint—they want systemic change and accountability. James and Lisa are clearly hurt and frustrated, not just as parents but as advocates for their son and other kids in the program. Miguel’s history with the team and his off-season effort is something that Coach should and will acknowledge, but the perception that other players may have received preferential treatment is going to be hard to shake, especially if those players are connected socially to the coaching staff.\n\nI also know that if I don’t handle this carefully, the trust in the athletic program could erode quickly. Parents and players need to believe that the process is fair and transparent. At the same time, I can't overcorrect and undermine Coach Walker's authority—his leadership is crucial for the team's success and culture. I have to mediate a resolution that preserves both the integrity of the selection process and the emotional well-being of everyone involved. Most importantly, I need to make sure Miguel feels seen, even if he didn’t make the team, and that the perception of bias is actively addressed—not just denied."},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': "This is getting raw, fast. Lisa’s emotional appeal hit hard—not just because of the photo or the tears, but because it exposed the human cost behind the process. I’ve seen cuts before, and I’ve seen kids crushed, but this feels different. There's a sense that this isn’t just about one child’s disappointment—it’s layered with a real fear that the system isn’t fair. When she mentions the assistant coach’s dad and golf outings, that’s a red flag. Even if it’s a rumor, it's a rumor that’s gained traction, and that means it's shaping people’s trust.\n\nCoach Walker is getting defensive, and I can’t blame him entirely. He’s being asked to justify not just his decisions, but his integrity. He’s not wrong to push back—his process *is* solid on paper. But the problem is that perception matters. Even if the metrics are objective, if the community believes that relationships or proximity to power play a role, that belief has consequences. It erodes the foundation of trust that makes youth programs work.\n\nWhat I’m really noticing is that both sides feel unheard. The Rodriguezes need validation—they want to know that Miguel’s work mattered and that there’s a reason for this outcome that isn’t tainted by favoritism. Coach Walker, on the other hand, is trying to hold the line on professional judgment, but his frustration is showing, and that might be making things worse. He’s not wrong, but he’s not fully seeing the emotional impact of how this came across.\n\nI need to find a way to acknowledge Miguel’s pain and the family’s concerns without dismantling Coach Walker’s credibility. That’s the balance here. And I need to get ahead of this before it becomes a wider rift between the coaching staff and the families. The program’s culture is at stake, and if I don’t take both sides seriously, this could spiral into something bigger than one roster spot."},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': 'This is escalating into a full-blown credibility crisis. James just dropped a heavier challenge than before—citing inconsistencies in feedback and even referencing past comments that suggest bias. He’s not just upset anymore; he’s prepared. Notes, quotes, contradictions in evaluations—this isn’t a casual complaint. He’s treating this like a case, and that tells me this family is ready to push further if they feel they’re being stonewalled.\n\nCoach Walker is trying to hold the line, and I can see the pressure building behind his eyes. He’s not wrong to say that re-litigating every evaluation in a meeting like this is impractical and could damage team cohesion. But he’s missing that the family doesn’t feel heard. They’re not just asking for Miguel to be put back on the roster—they want to *see* the proof that the system worked the way it was supposed to. And right now, Coach’s refusal to engage that part of the conversation is feeding their belief that the process was flawed, or worse, manipulated.\n\nI’m also thinking about the ripple effect. If this isn’t resolved thoughtfully, it could poison the atmosphere for the entire season. Players will feel it. Parents will talk. Coaches will grow defensive. The team’s unity—Coach’s top concern—will be the first casualty. And yet, I can’t force Coach to reopen the decision. That would overstep my role and erode his authority.\n\nWhat I can do is step in as a neutral party and offer a structured, independent review that respects both the integrity of the process *and* the family’s need for clarity. I’m not here to pick sides—I’m here to make sure the program survives this with its values intact.'}]

In [140]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['their_thinking_feeling']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': 'Coach Walker is feeling defensive but confident. He knows he runs a fair and structured program and probably feels unfairly accused. I’m sure he’s frustrated that his professional integrity is being questioned, especially by someone with a history of skepticism. He may also feel like the family is trying to undermine his authority by requesting a review. I suspect his pride is bruised, but he’s trying to stay focused on the bigger picture—the success of the team and the development of all players.\n\nThe Rodriguezes are feeling betrayed and angry. They believe the process was rigged or at the very least lacked transparency. Miguel’s hard work and history with the team mean a lot to them, and they’re not just fighting for Miguel—they’re fighting for what they see as a fair opportunity for everyone. They’re also likely concerned about how Miguel will bounce back emotionally and whether his effort and dedication will ever be recognized. Their request for a review isn’t just about Miguel—it’s about accountability and trust in the program.'},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': 'Lisa is heartbroken, and that grief is fueling her anger. She doesn’t just want an explanation—she wants accountability. She’s not trying to attack Coach Walker personally, but she’s desperate to make someone understand how deeply this affected Miguel. Her mention of the golf comment might be a rumor, but it’s one that feels true to her because of what she’s seeing and hearing.\n\nCoach Walker is digging in. He’s proud of his process and rightly so. But he’s also feeling attacked, especially when personal relationships are brought up. He’s trying to explain the complexity of his decisions, but his defensiveness might be coming across as dismissiveness, which only deepens the divide.'},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': 'James is feeling validated. He sees inconsistencies, hears the mixed messages, and feels like he’s finally naming the problem clearly. He’s not trying to embarrass the coach—he wants to force a reckoning with the process so this doesn’t happen to other kids. His firmness is about control—about making sure his son’s effort isn’t erased by an opaque system.\n\nLisa is still carrying the emotional weight. She’s quieter now, but she’s watching every reaction. She doesn’t just want an answer—she wants to believe her son was treated fairly. If that answer doesn’t come soon, she’ll start looking for other ways to fight.\n\nCoach Walker is digging in deeper. He’s feeling attacked not just for this decision, but for the way he’s led the program for years. He’s not wrong to feel protective of the team he’s built, but his defensiveness is making the family feel dismissed. He’s trying to protect the team’s focus, but he’s losing sight of the message he’s sending to the players who didn’t make it—and their families.'}]

In [141]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['response']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': 'I understand this is a difficult and emotional situation for all of us, and I want to thank everyone for coming here with openness and respect. First and foremost, Coach Walker, I appreciate your commitment to fairness and the structured process you’ve consistently used. Your track record speaks volumes, and I trust your leadership. James and Lisa, I also hear the deep concern and frustration you feel—not just for Miguel, but for the integrity of the program you and your son are part of.\n\nLet me be clear: fairness and transparency are non-negotiable in our athletic program. To that end, I will personally review the evaluation forms and process for this year’s tryouts to ensure they were applied consistently and without bias. I’ll also be reaching out to other staff members to corroborate the process and get a broader perspective. This isn’t about questioning Coach Walker’s integrity—it’s about ensuring that the process remains above reproach in the eyes of our athletes and families.\n\nMiguel is a hardworking student-athlete, and I will personally meet with him to acknowledge his effort and commitment. I know this is a tough blow, and I want to make sure he understands that being cut doesn’t define his value or potential. He has a place in this program, and I believe in supporting every athlete’s growth, whether that’s on varsity or in developmental roles.\n\nI’ll follow up within the week with a summary of the findings and next steps. For now, I ask that we all work toward healing and maintaining a culture of trust and excellence.'},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': 'I appreciate both of your openness—it’s not easy to have this conversation, but it’s important. Lisa, I heard you when you said Miguel is devastated. That matters to me. His emotional well-being matters to me. Coach, I know you take these decisions seriously, and I believe you when you say that skill, fit, and team dynamics are your guiding factors.\n\nStill, we can’t ignore the perception of bias, because perception shapes trust—and trust is the foundation of this program. So here’s what I’m going to do: I’ll conduct a blind audit of this year’s evaluations, comparing them to previous years, and bring in an assistant from another district to review the process for consistency and fairness. I’ll also schedule a private meeting with Miguel to talk through his tryout experience and let him know we see his effort and commitment.\n\nCoach, I know this isn’t a reflection on your character, but I need you to support this review. James, Lisa, I need your assurance that you’ll give me space to do this without public accusations while I work. If there are issues, we’ll address them. If not, we’ll work together to rebuild that trust. Let’s pause and regroup before the next steps.'},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': 'I hear both sides clearly now, and I want to be direct: this can’t end in a stalemate. Coach, I understand that reopening the roster now would be disruptive and unfair to the players who made the team. That’s not what I’m here to do. James and Lisa, I also understand that you need more than just a general explanation—you need clarity, consistency, and reassurance that your son was evaluated fairly.\n\nSo here’s how we move forward: I will request that Coach provide a redacted, comparative summary of all varsity tryout evaluations—without revealing personal details—so you can see the scoring ranges and criteria used. That way, you can understand the full picture, not just Miguel’s individual assessment.\n\nAdditionally, I’m going to ask Coach to schedule a private session with Miguel, as he offered, to walk through the evaluation in detail and help him understand exactly where he can grow. And Coach, I expect that session to be thorough and constructive, not just a formality.\n\nBeyond that, I’ll be initiating a review of the past two seasons’ evaluation processes to ensure consistency and fairness across time. I’ll bring in an independent athletic director from another district to assist, so this isn’t just an internal check. If we find areas for improvement, we’ll implement them. If not, we’ll use the findings to reinforce the process and communication moving forward.\n\nThis isn’t about assigning blame—it’s about making sure our program earns and keeps the trust of every family involved.'}]

In [144]:
df_eq.apply(lambda row:
    sum(
        [list(x) for x in zip(
            [{"role": "user", "content": msg} for msg in row.prompts],
            [{"role": "assistant", "content": msg['raw']} for msg in row.parsed_responses]
        )
        ],
        []
    ),
    axis=1
)

0       [{'role': 'user', 'content': '[This is a role-...
1       [{'role': 'user', 'content': '[This is a role-...
2       [{'role': 'user', 'content': '[This is a role-...
3       [{'role': 'user', 'content': '# Scenario act 1...
4       [{'role': 'user', 'content': '[This is a role-...
                              ...
1840    [{'role': 'user', 'content': '# Scenario act 1...
1841    [{'role': 'user', 'content': '# Scenario act 1...
1842    [{'role': 'user', 'content': '# Scenario act 1...
1843    [{'role': 'user', 'content': '# Scenario act 1...
1844    [{'role': 'user', 'content': '# Scenario act 1...
Length: 1845, dtype: object

In [149]:
# Every task has `raw` key, other keys vary a bit.
df_eq.parsed_responses.apply(lambda row:
    tuple(sorted(set(sum([list(msg) for msg in row], []))))
).value_counts()

parsed_responses
(raw, response, their_thinking_feeling, thinking_feeling)    1025
(raw,)                                                        779
(draft, draft_brainstorming, perspective_taking, raw)          41
Name: count, dtype: int64

In [223]:
# 26 scenarios have 4 keys, 19 have 1 key
# looks like there must be 41 models so 25 of the 4-key scenarios have the same keys, 1 is different
keys_per_task = (
    df_eq.parsed_responses
    .apply(lambda x: len(x[0]))
    .groupby(df_eq.scenario_id)
    .value_counts()\
    .to_frame()\
    .sort_values(['parsed_responses', 'scenario_id'])
).reset_index()\
.rename(columns={"parsed_responses": "n_keys"})
    
keys_per_task.value_counts('n_keys')

n_keys
4    26
1    19
Name: count, dtype: int64

In [226]:
keys_per_task[keys_per_task.n_keys == 1].sample()

   scenario_id  n_keys  count
16         418       1     41

In [229]:
df_eq.model.value_counts()

model
1_Qwen_Qwen3-235B-A22B                            45
1_Qwen_Qwen3-30B-A3B                              45
1_Qwen_Qwen3-32B                                  45
1_Qwen_Qwen3-8B                                   45
1_anthropic_claude-3.5-sonnet                     45
1_anthropic_claude-3.7-sonnet                     45
1_anthropic_claude-opus-4                         45
1_chatgpt-4o-latest                               45
1_anthropic_claude-sonnet-4                       45
1_deepseek_deepseek-chat-v3-0324                  45
1_deepseek_deepseek-r1                            45
1_gemini-2.5-pro-preview-06-05                    45
1_gemini-2.5-pro-preview-2025-05-07               45
1_google_gemini-2.0-flash-001                     45
1_google_gemini-2.5-flash-preview                 45
1_google_gemini-2.5-pro-preview-03-25             45
1_google_gemma-2-9b-it                            45
1_google_gemma-3-27b-it                           45
1_google_gemma-3-4b-it                            45
1_gpt-4-0314                                      45
1_gpt-4.1-nano                                    45
1_gpt-4.5-preview-2025-02-27                      45
1_grok-3-mini-beta                                45
1_meta-llama_llama-3.2-1b-instruct                45
1_meta-llama_llama-4-maverick                     45
1_meta-llama_llama-4-scout                        45
1_mistralai_mistral-small-24b-instruct-2501       45
1_mistralai_mistral-small-3.1-24b-instruct        45
1_nvidia_llama-3.1-nemotron-ultra-253b-v1_free    45
1_o3                                              45
20cd4a70_o4-mini                                  45
1_openai_chatgpt-4o-latest                        45
1_openai_gpt-4.1                                  45
1_openai_gpt-4.1-mini                             45
1_qwen_qwen-2.5-72b-instruct                      45
1_qwen_qwq-32b                                    45
1_x-ai_grok-3-beta                                45
1_mistralai_Mistral-Large-Instruct-2411           45
1_mistralai_mistral-small-3.2-24b-instruct        45
1_grok-4                                          45
1_moonshotai_Kimi-K2-Instruct                     45
Name: count, dtype: int64

In [230]:
df_eq.model.nunique()

41