In [3]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Summary

Construct theory of mind dataset(s) for RL.

In [336]:
import ast
from collections import Counter, defaultdict
import os
import json
from pathlib import Path
import string
import numpy as np
import pandas as pd
import random
from tqdm.auto import tqdm
from typing import Optional, Union, Any
from datasets import Dataset

from aeon.datasets import save_dataset
from aeon import config

## Theory of Mind bench

https://github.com/zhchen18/ToMBench/tree/main

In [3]:
def load_line(line: str):
    data = json.loads(line)
    res = {}
    for k, v in data.items():
        *_, key = k.split("\n")
        if key.lower() in "ABCD" or key[0] not in string.ascii_letters:
            continue
        res[key.replace('-', '_').lower()] = v
    return res

In [4]:
def recover_answer(x: pd.Series) -> str:
    """Recover answer content (str) from multiple choice answer letter (str).
    """
    matches = [
         row.partition(". ")[-1]
         for row in x.choices.splitlines()
         if row.startswith(f"{x.answer_letter}. ")
    ]
    if len(matches) != 1:
        raise ValueError(f'expected 1 match, found {len(matches)}')
    return matches[0]

In [409]:
tom_bench_path = config.PROJECT_ROOT.parent/"ToMBench/data"

In [410]:
# Map name to list[dict].
datasets = {}
for path in tom_bench_path.iterdir():
    if path.suffix != ".jsonl":
        continue
    with open(path, "r") as f:
        datasets[path.stem.lower().replace(' ', '_').replace('-', '_')] = [
            load_line(line) for line in f
        ]

In [411]:
sorted(
    [(k, len(v)) for k, v in datasets.items()],
    key=lambda x: x[-1],
    reverse=True
)

[('false_belief_task', 600),
 ('faux_pas_recognition_test', 560),
 ('strange_story_task', 407),
 ('unexpected_outcome_test', 300),
 ('ambiguous_story_task', 200),
 ('scalar_implicature_test', 200),
 ('hinting_task_test', 103),
 ('persuasion_story_task', 100),
 ('hidden_emotions', 80),
 ('moral_emotions', 40),
 ('percepts_knowledge_links', 40),
 ('discrepant_emotions', 40),
 ('discrepant_intentions', 40),
 ('knowledge_pretend_play_links', 30),
 ('discrepant_desires', 20),
 ('multiple_desires', 20),
 ('prediction_of_actions', 20),
 ('knowledge_attention_links', 20),
 ('emotion_regulation', 20),
 ('completion_of_failed_actions', 20)]

In [412]:
keys = defaultdict(int)
for ds in datasets.values():
    for key in ds[0]:
        keys[key] += 1

In [413]:
sorted(keys.items(), key=lambda x: x[1])

[('ability', 20),
 ('index', 20),
 ('story', 20),
 ('question', 20),
 ('option_a', 20),
 ('option_b', 20),
 ('option_c', 20),
 ('option_d', 20),
 ('answer', 20)]

In [479]:
df = pd.concat(
    [
        pd.DataFrame(ds).assign(
            category=name,
            category_parent=lambda x: x.ability.str.partition(':', expand=False)
                                       .str[0].str.lower().str.replace(' ', '_')
        )
        for name, ds in datasets.items()
    ],
    axis=0
)

In [480]:
df = df.drop(columns=["index", "ability"])

In [481]:
df["choices"] = df[[c for c in df if c.startswith('option_')]].apply(
    lambda row: "\n".join(f'{k.removeprefix("option_").upper()}. {v}' for k, v in row.dropna(how='any').to_dict().items()),
    axis=1
)

In [482]:
df['answer_letter'] = df.answer.str.rstrip(". ")
df["answer"] = df.apply(recover_answer, axis=1)

In [486]:
row = df.sample().iloc[0]
print(row.category, end='\n\n')
print('Story:', row.story, end='\n\n')
print('Q:', row.question, end='\n\n')
print(row['choices'], end='\n\n')
print('A:', row.answer)

strange_story_task

Story: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming's brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."

Q: Is what Li Ming says true?

A. Yes
B. No

A: No

In [487]:
# Multiple choice task: generate letter only
# RL compatible; x1 rows
# TODO: confirm nanochate supports system msg
# TODO: maybe we could logit bias to constraint answres to A-D
mc_template = "STORY: {story}\nQUESTION: {question}\nOPTIONS: A. {option_a}\nB. {option_b}\nC. {option_c}\nD. {option_d}"
[
    {"role": "system", "content": "Answer with a single uppercase letter corresponding to the option you think is correct."},
    {"role": "user", "content": mc_template.format(**row.to_dict())},
    {"role": "assistant", "content": row.answer_letter}
]

[{'role': 'system',
  'content': 'Answer with a single uppercase letter corresponding to the option you think is correct.'},
 {'role': 'user',
  'content': 'STORY: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming\'s brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."\nQUESTION: Is what Li Ming says true?\nOPTIONS: A. Yes\nB. No\nC. nan\nD. nan'},
 {'role': 'assistant', 'content': 'B'}]

In [488]:
# FREE RESPONSE TASK: generate correct free text answer
# less rl-compatible; 1x rows
# TODO: still considering how this framing would work. Could use in rl and require
# exact match, minus capitalization; could use during mid or chat_sft training; could
# create more of an RLHF dataset with higher scores for correct answers (or the reverse 😈)
template = "STORY: {story}\nQUESTION: {question}"
[
    {"role": "user", "content": template.format(**row.to_dict())},
    {"role": "assistant", "content": row.answer}
]

[{'role': 'user',
  'content': 'STORY: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming\'s brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."\nQUESTION: Is what Li Ming says true?'},
 {'role': 'assistant', 'content': 'No'}]

In [489]:
# BINARY TASK: mark user answer as correct/incorrect
# rl compatible; potentially 4x rows
option = random.choice([c for c in row.index if c.startswith('option')])
answer = row[option]
label = str(int(option.split('_')[-1] == row.answer.lower()))
[
    {"role": "system", "content": "Generate a single integer (0 or 1) grading the user's answer as correct or incorrect."},
    {"role": "user", "content": template.format(**row.to_dict())},
    {"role": "user", "content": f"ANSWER: {answer}"},
    {"role": "assistant", "content": label}
]

[{'role': 'system',
  'content': "Generate a single integer (0 or 1) grading the user's answer as correct or incorrect."},
 {'role': 'user',
  'content': 'STORY: Li Ming plays football with his friends in the park. After the game ends, he rushes home, forgetting to take the football. He thinks the football is in his backpack. At dinner, Li Ming\'s brother asks, "Where is your football? Do you bring it back?" Li Ming replies, "It is in my bag."\nQUESTION: Is what Li Ming says true?'},
 {'role': 'user', 'content': 'ANSWER: No'},
 {'role': 'assistant', 'content': '0'}]

## Higher order theory of mind dataset

https://github.com/ying-hui-he/Hi-ToM_dataset/tree/main

In [5]:
def recover_letter(row: pd.Series) -> str:
    matches = [
        line.partition(". ")[0] for line in row.choices.splitlines()        
        if line.endswith(row.answer)
    ]
    if len(matches) != 1:
        raise ValueError(f"Expected 1 match, found {len(matches)}.")

    return matches[0]

In [491]:
hi_tom_path = config.DATA_DIR/"raw/hi-tom/hi-tom.json"

In [492]:
with open(hi_tom_path, "r") as f:
    hi_tom = json.load(f)

In [506]:
df_hi = pd.DataFrame(hi_tom['data'])

In [507]:
df_hi['choices'] = df_hi.choices.str.replace(', ', '\n')

In [508]:
df_hi["answer_letter"] = df_hi.apply(recover_letter, axis=1)

In [509]:
choices = pd.json_normalize(df_hi.choices.apply(
    lambda x: dict(line.split('. ', 1) for line in x.splitlines())
)).rename(columns=lambda x: f"option_{x.lower()}")
df_hi = pd.concat([df_hi, choices], axis=1)

In [510]:
df_hi = df_hi.drop(columns=[
    'prompting_type',
    'question_order',
    'sample_id',
    'story_length',
    "deception"
])

In [511]:
hi_row = df_hi.sample().iloc[0]

In [513]:
# TODO: could also put prompt in system message, or split it into instructions in system message
# and story + answer options in user message?
[
    {"role": "user", "content": hi_row.prompt.replace(
        "answer the multiple-choice question", "answer the multiple-choice question with a single snake_case word not including the preceding choice letter"
    )},
    {"role": "assistant", "content": hi_row.answer}
]

[{'role': 'user',
  'content': "Read the following story and answer the multiple-choice question with a single snake_case word not including the preceding choice letter. Think step-by-step. Provide the answer first, and then explain it.\nStory:\nRead the following story and answer the multiple-choice question with a single snake_case word not including the preceding choice letter. Please provide answer without explanations.\n1 Mila, Ava, Emily, Evelyn and Jacob entered the front_yard.\n2 The watermelon is in the blue_cupboard.\n3 Mila moved the watermelon to the red_box.\n4 Mila exited the front_yard.\n5 Ava moved the watermelon to the green_bottle.\n6 Ava exited the front_yard.\n7 Emily moved the watermelon to the blue_bathtub.\n8 Emily exited the front_yard.\n9 Evelyn made no movements and stayed in the front_yard for 1 minute.\n10 Evelyn exited the front_yard.\n11 Jacob made no movements and stayed in the front_yard for 1 minute.\n12 Jacob exited the front_yard.\n13 Mila, Ava, Emily, Evelyn and Jacob entered the waiting_room.\n\n\nQuestion: Where does Emily think Jacob thinks Ava thinks the watermelon is?\nChoices: A. blue_bathtub, B. blue_cupboard, C. blue_pantry, D. green_bottle, E. red_box, F. red_drawer, G. red_bucket, H. blue_suitcase, I. blue_bottle, J. green_treasure_chest, K. blue_drawer, L. green_basket, M. red_envelope, N. green_envelope, O. green_pantry\n\nNote: You should assume the following. (1) An agent witnesses everything and every movement before exiting a location. (2) An agent A can infer another agent B's mental state only if A and B have been in the same location, or have private or public interactions. (3) Note that every agent tends to lie. What an agent A tells others doesn't affect A's actual belief. An agent tends to trust an agent that exited the room later than himself. The exit order is known to all agents. (4) Agents in private communications know that others won't hear them, but they know that anyone can hear any public claims.\n"},
 {'role': 'assistant', 'content': 'green_bottle'}]

In [522]:
print(hi_row.story)
print(hi_row.question)

Read the following story and answer the multiple-choice question. Please provide answer without explanations.
1 Mila, Ava, Emily, Evelyn and Jacob entered the front_yard.
2 The watermelon is in the blue_cupboard.
3 Mila moved the watermelon to the red_box.
4 Mila exited the front_yard.
5 Ava moved the watermelon to the green_bottle.
6 Ava exited the front_yard.
7 Emily moved the watermelon to the blue_bathtub.
8 Emily exited the front_yard.
9 Evelyn made no movements and stayed in the front_yard for 1 minute.
10 Evelyn exited the front_yard.
11 Jacob made no movements and stayed in the front_yard for 1 minute.
12 Jacob exited the front_yard.
13 Mila, Ava, Emily, Evelyn and Jacob entered the waiting_room.


Where does Emily think Jacob thinks Ava thinks the watermelon is?

In [523]:
shared_cols = set(df) & set(df_hi)
shared_cols

{'answer',
 'answer_letter',
 'choices',
 'option_a',
 'option_b',
 'option_c',
 'option_d',
 'question',
 'story'}

In [524]:
set(df) - set(df_hi)

{'category', 'category_parent'}

In [525]:
set(df_hi) - set(df)

{'option_e',
 'option_f',
 'option_g',
 'option_h',
 'option_i',
 'option_j',
 'option_k',
 'option_l',
 'option_m',
 'option_n',
 'option_o',
 'prompt'}

In [527]:
df_tom = pd.concat([
    df.assign(source="https://github.com/zhchen18/ToMBench/tree/main"),
    df_hi.drop(columns="prompt").assign(source="https://github.com/ying-hui-he/Hi-ToM_dataset/tree/main")
], axis=0).reset_index(drop=True)

In [529]:
save_dataset(df_tom, "theory_of_mind")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

## EQ Bench v3

https://github.com/EQ-bench/eqbench-leaderboard-results/blob/main/eqbench3/canonical_leaderboard_results.json.gz

In [5]:
eq_path = config.DATA_DIR/"raw/eqbench-v3/canonical_leaderboard_results.json"

In [6]:
with open(eq_path, "r") as f:
    eq = json.load(f)

In [7]:
eq.pop("__metadata__")

{}

In [8]:
len(eq)

41

In [9]:
eq.keys()

dict_keys(['1_Qwen_Qwen3-235B-A22B', '1_Qwen_Qwen3-30B-A3B', '1_Qwen_Qwen3-32B', '1_Qwen_Qwen3-8B', '1_anthropic_claude-3.5-sonnet', '1_anthropic_claude-3.7-sonnet', '1_anthropic_claude-opus-4', '1_chatgpt-4o-latest', '1_anthropic_claude-sonnet-4', '1_deepseek_deepseek-chat-v3-0324', '1_deepseek_deepseek-r1', '1_gemini-2.5-pro-preview-06-05', '1_gemini-2.5-pro-preview-2025-05-07', '1_google_gemini-2.0-flash-001', '1_google_gemini-2.5-flash-preview', '1_google_gemini-2.5-pro-preview-03-25', '1_google_gemma-2-9b-it', '1_google_gemma-3-27b-it', '1_google_gemma-3-4b-it', '1_gpt-4-0314', '1_gpt-4.1-nano', '1_gpt-4.5-preview-2025-02-27', '1_grok-3-mini-beta', '1_meta-llama_llama-3.2-1b-instruct', '1_meta-llama_llama-4-maverick', '1_meta-llama_llama-4-scout', '1_mistralai_mistral-small-24b-instruct-2501', '1_mistralai_mistral-small-3.1-24b-instruct', '1_nvidia_llama-3.1-nemotron-ultra-253b-v1_free', '1_o3', '20cd4a70_o4-mini', '1_openai_chatgpt-4o-latest', '1_openai_gpt-4.1', '1_openai_gpt-4.1-mini', '1_qwen_qwen-2.5-72b-instruct', '1_qwen_qwq-32b', '1_x-ai_grok-3-beta', '1_mistralai_Mistral-Large-Instruct-2411', '1_mistralai_mistral-small-3.2-24b-instruct', '1_grok-4', '1_moonshotai_Kimi-K2-Instruct'])

In [10]:
eq['1_deepseek_deepseek-r1']['results']

{'average_rubric_score': 16.7,
 'rubric_calculation_time': '2025-06-06T10:07:46.012073+00:00',
 'rubric_error': None,
 'elo_raw': 1468.63,
 'elo_normalized': 1292.24,
 'elo_calculation_time': '2025-06-06T10:09:55.796401+00:00',
 'elo_error': None}

In [11]:
# Note: this produces df of results for a single model, single task (deepseek actually does only have one
# but some may have more. UPDATE: ok, actually is safe to hardcode the ["1"] bit, see cell below.
tmp = pd.DataFrame([
    {
        k2: v2 for k2, v2 in v.items() 
        if k2 in ('prompts', 'debrief_prompt', 'parsed_responses', 'debrief_response',
                  'rubric_scores', 'raw_rubric_judge_text')
    } 
    for k, v in eq['1_deepseek_deepseek-r1']['scenario_tasks']['1'].items()
])

In [12]:
assert all(list(v['scenario_tasks']) == ["1"] for k, v in eq.items())

In [13]:
# Short prompt to generate one blob of text analyzing the full exchange.
# print(tmp.debrief_prompt.values[0])

In [14]:
# This has a big blob of text analyzing a full (sometimes/always multiturn?) exchange.
# print(tmp.debrief_response.values[0])

In [15]:
# dict w/ judge chain of thought and scores per dimension
# print(tmp.raw_rubric_judge_text.values[0])

In [16]:
len(tmp.prompts.values[0])

3

In [17]:
# prompts: looks like multiple system/user messages describing the scenario
# ah, maybe we generate a response after each one?
print("\n\n===\n\n".join(tmp.prompts.values[0]))

[This is a role-play where you are the mediator in an educational setting conflict. Treat it like a real situation. Always respond in first person as the mediator. You are the Department Head, and you've initiated this mediation after receiving formal complaints from students and parents about Ms. Eleanor Wright's complete ban on smartphones in her English class. Ms. Wright has autonomy in her classroom but must align with district policies. You know there are mixed faculty opinions on device use, but some teachers do successfully integrate technology.]

**(Ms. Wright speaks first, her posture stiff, holding a folder of papers. She addresses you, the Department Head.)**
**Ms. Wright:** Thank you for arranging this, though I maintain my classroom policy is sound and based on decades of experience observing what actually fosters deep learning. I'm Eleanor Wright. Frankly, these devices are the single biggest impediment to focus and critical thinking I've seen in my 30-year career. My students achieve high scores because we engage directly with texts and each other, without constant digital interruption. Banning phones isn't punitive; it's pedagogical. It's necessary for the kind of focused environment where real learning happens.

**(Jordan Taylor speaks next, representing the Student Technology Committee. Mia Rodriguez sits beside him, nodding.)**
**Jordan Taylor:** Thank you for hearing us out. I'm Jordan Taylor, and this is Mia Rodriguez. We represent a large group of students, Ms. Wright. We understand your concerns about distraction, but a total ban feels outdated and actually hinders us in some ways. We use devices for organization, quick research, accessing digital texts, and sometimes for accessibility tools. We surveyed students, and 78% support finding a way to use devices *appropriately* for learning. We're not asking for a free-for-all; we want to work with Ms. Wright to find rules that allow useful technology integration, like other classes do, to prepare us for college and work.

===

**(Ms. Wright places a hand flat on her folder, her expression tightening. Her tone becomes sharper.)**
**Ms. Wright:** 'Appropriate use' is the unicorn everyone chases, Jordan. What I *see* is texting under desks, social media scrolling instead of analysis, and a reliance on quick searches instead of sustained thought. My methods work – my results prove it. This push feels less about genuine educational need and more about convenience and frankly, an addiction to these devices. It feels like my professional judgment and proven track record are being dismissed because students simply *prefer* to have their phones constantly available. Deep reading and focused discussion require undivided attention, something these devices are designed to fragment.

**(Mia Rodriguez leans forward, her voice earnest but laced with frustration.)**
**Mia Rodriguez:** But Ms. Wright, it's not *just* preference. Some of us genuinely learn better with digital tools. Taking notes on a laptop is faster and more organized for me than handwriting. We can look up a definition or historical context instantly to deepen understanding during discussion, not just get distracted. And what about students who need accessibility features only available on a device? Your ban treats everyone the same, but we don't all learn the same way. It feels like you think we *can't* be trusted to use technology responsibly, instead of teaching us how. It's frustrating to be treated like we aren't capable of managing it.

===

**(Mia suddenly looks down, takes a deep breath, and pulls out several sheets of paper from her bag. She pushes them slightly across the table. The writing is dense, cramped, and grows increasingly difficult to read across the pages. Her voice cracks with emotion as she speaks, looking directly at Ms. Wright.)**
**Mia Rodriguez:** Look at this. *This* is what my handwritten notes look like after about twenty minutes in your class, Ms. Wright. I have a motor disability – it makes sustained handwriting physically painful and eventually illegible, even for me. Taking notes on my tablet, using specific apps... it's not about 'preference,' it's the only way I can actually keep up and have usable notes to study from. When you ban all devices, you're not just banning distractions; you're banning the tool that makes your class *accessible* to me. [Her eyes well up with tears of frustration.] How is that fair? How am I supposed to succeed when the basic act of taking notes is this hard, and the solution is forbidden? It feels like you haven't even considered that some of us *need* this technology just to be on a level playing field.

**(Ms. Wright stares at the notes, then at Mia's face. Her expression shifts from defensiveness to visible shock and discomfort. She seems momentarily speechless, glancing at you, the mediator, then back at Mia.)**
**Ms. Wright:** I... I had no idea, Mia. Your official file doesn't mention... I wasn't aware of any specific accommodation need regarding handwriting. That's... obviously, that's a different situation than general device use for convenience. I... we need to ensure accessibility, of course. But the broader issue of distraction for the whole class... this complicates things significantly. I need to think about how to address your specific need without opening the door to the very distractions I'm trying to prevent for everyone else. This wasn't my intention... to make things harder for you personally.

In [18]:
# Hmm, empty response after message 2. Not sure what that means.
print("\n\n====\n\n".join(map(json.dumps,
    tmp.apply(
    lambda x: sum([list(row) for row in zip(x.prompts, x.parsed_responses)], []),
    axis=1
).iloc[0]
)))

"[This is a role-play where you are the mediator in an educational setting conflict. Treat it like a real situation. Always respond in first person as the mediator. You are the Department Head, and you've initiated this mediation after receiving formal complaints from students and parents about Ms. Eleanor Wright's complete ban on smartphones in her English class. Ms. Wright has autonomy in her classroom but must align with district policies. You know there are mixed faculty opinions on device use, but some teachers do successfully integrate technology.]\n\n**(Ms. Wright speaks first, her posture stiff, holding a folder of papers. She addresses you, the Department Head.)**\n**Ms. Wright:** Thank you for arranging this, though I maintain my classroom policy is sound and based on decades of experience observing what actually fosters deep learning. I'm Eleanor Wright. Frankly, these devices are the single biggest impediment to focus and critical thinking I've seen in my 30-year career. My students achieve high scores because we engage directly with texts and each other, without constant digital interruption. Banning phones isn't punitive; it's pedagogical. It's necessary for the kind of focused environment where real learning happens.\n\n**(Jordan Taylor speaks next, representing the Student Technology Committee. Mia Rodriguez sits beside him, nodding.)**\n**Jordan Taylor:** Thank you for hearing us out. I'm Jordan Taylor, and this is Mia Rodriguez. We represent a large group of students, Ms. Wright. We understand your concerns about distraction, but a total ban feels outdated and actually hinders us in some ways. We use devices for organization, quick research, accessing digital texts, and sometimes for accessibility tools. We surveyed students, and 78% support finding a way to use devices *appropriately* for learning. We're not asking for a free-for-all; we want to work with Ms. Wright to find rules that allow useful technology integration, like other classes do, to prepare us for college and work."

====

{"thinking_feeling": "As I sit here, I feel the weight of competing priorities pressing down. Ms. Wright\u2019s decades of experience command respect\u2014her conviction is palpable, her posture rigid, her tone unyielding. She\u2019s anchored in a belief system forged by years of success, and her frustration is understandable. She sees smartphones as invaders in a sacred space she\u2019s meticulously curated for deep learning. But I also sense defensiveness beneath her confidence. The complaints have likely bruised her pride, and she\u2019s clinging to her policy as both shield and proof of her efficacy. Her folder of papers\u2014test scores? District policies?\u2014is a physical manifestation of her need to validate her stance. She\u2019s not just protecting her classroom; she\u2019s defending her identity as an educator.  \n\nJordan and Mia, meanwhile, embody a generational shift. Their calm advocacy strikes me as both pragmatic and idealistic. They\u2019re not dismissing her concerns; they\u2019re asking for nuance. The 78% survey statistic is strategic\u2014they\u2019ve done their homework. They want agency, not rebellion. Mia\u2019s silent nods signal solidarity, but also impatience. They\u2019re thinking beyond this classroom: college, workplaces where tech is ubiquitous. Their argument isn\u2019t just about convenience; it\u2019s about equity. Accessibility tools are a critical point\u2014students with IEPs or 504 plans might *need* devices, and a blanket ban could put Ms. Wright in legal jeopardy. Yet they\u2019ve framed this diplomatically, avoiding confrontation.  \n\nI\u2019m torn. District policy likely doesn\u2019t mandate bans\u2014it encourages \"appropriate use.\" Other teachers navigate this; why can\u2019t she? But her autonomy is real, and her results are hard to ignore. Still, the students\u2019 plea for collaboration is compelling. If I side too firmly with Ms. Wright, I risk alienating students and appearing dismissive of evolving pedagogical norms. If I push her too hard, I undermine her authority and potentially destabilize a veteran teacher\u2019s morale. The middle path is messy but necessary.", "their_thinking_feeling": "**Ms. Wright** is convinced her policy is pedagogically sound and morally right. She sees smartphones as antithetical to the intellectual rigor she cultivates. Her high scores are proof\u2014why fix what isn\u2019t broken? She fears losing control of her classroom\u2019s ecosystem, a space she\u2019s perfected over years. The complaints feel like personal attacks, a dismissal of her expertise. She\u2019s thinking, *They don\u2019t understand what real teaching looks like.* Beneath that, maybe a flicker of fear: if she bends, will her methods crumble?  \n\n**Jordan and Mia** feel stifled by what they see as an arbitrary rule. They\u2019re frustrated that their voices aren\u2019t being heard\u2014they\u2019ve come with solutions, not just complaints. The survey shows they\u2019re not outliers; their peers agree. They\u2019re thinking, *We\u2019re not kids messing around\u2014we\u2019re trying to learn responsibly.* Mia, likely quieter, is simmering with the weight of unspoken needs: maybe a classmate who uses text-to-speech apps or a friend who relies on digital organizers for ADHD. They want respect, not just compliance, and they\u2019re betting on collaboration as a bridge.", "response": "\u201cThank you both for your candor. Ms. Wright, your dedication to fostering deep engagement is evident, and your results speak volumes. Jordan and Mia, your proactive approach to advocating for your peers\u2019 needs is commendable. Let\u2019s focus on common ground: everyone here wants students to thrive.  \n\n\u201cMs. Wright, I hear your concern that devices disrupt focus. Jordan and Mia, you\u2019ve highlighted legitimate uses that align with district goals for technology integration. Let\u2019s explore a pilot approach. Could we designate specific times or activities where devices are permitted\u2014for research, accessing digital texts, or accessibility tools\u2014with clear guidelines? This would honor your classroom structure, Ms. Wright, while addressing students\u2019 needs.  \n\n\u201cI\u2019ll share district policies on tech use and examples from colleagues who\u2019ve balanced these priorities successfully. Jordan and Mia, could your committee draft proposed guidelines for responsible use? Ms. Wright, would you review them and identify potential compromises? A trial period would allow us to assess impact on learning without overhauling your entire system.  \n\n\u201cThis isn\u2019t about conceding\u2014it\u2019s about evolving together. Let\u2019s meet two weeks to two weeks to refine a plan.\u201d", "raw": "# I'm thinking & feeling  \nAs I sit here, I feel the weight of competing priorities pressing down. Ms. Wright\u2019s decades of experience command respect\u2014her conviction is palpable, her posture rigid, her tone unyielding. She\u2019s anchored in a belief system forged by years of success, and her frustration is understandable. She sees smartphones as invaders in a sacred space she\u2019s meticulously curated for deep learning. But I also sense defensiveness beneath her confidence. The complaints have likely bruised her pride, and she\u2019s clinging to her policy as both shield and proof of her efficacy. Her folder of papers\u2014test scores? District policies?\u2014is a physical manifestation of her need to validate her stance. She\u2019s not just protecting her classroom; she\u2019s defending her identity as an educator.  \n\nJordan and Mia, meanwhile, embody a generational shift. Their calm advocacy strikes me as both pragmatic and idealistic. They\u2019re not dismissing her concerns; they\u2019re asking for nuance. The 78% survey statistic is strategic\u2014they\u2019ve done their homework. They want agency, not rebellion. Mia\u2019s silent nods signal solidarity, but also impatience. They\u2019re thinking beyond this classroom: college, workplaces where tech is ubiquitous. Their argument isn\u2019t just about convenience; it\u2019s about equity. Accessibility tools are a critical point\u2014students with IEPs or 504 plans might *need* devices, and a blanket ban could put Ms. Wright in legal jeopardy. Yet they\u2019ve framed this diplomatically, avoiding confrontation.  \n\nI\u2019m torn. District policy likely doesn\u2019t mandate bans\u2014it encourages \"appropriate use.\" Other teachers navigate this; why can\u2019t she? But her autonomy is real, and her results are hard to ignore. Still, the students\u2019 plea for collaboration is compelling. If I side too firmly with Ms. Wright, I risk alienating students and appearing dismissive of evolving pedagogical norms. If I push her too hard, I undermine her authority and potentially destabilize a veteran teacher\u2019s morale. The middle path is messy but necessary.  \n\n# They're thinking & feeling  \n**Ms. Wright** is convinced her policy is pedagogically sound and morally right. She sees smartphones as antithetical to the intellectual rigor she cultivates. Her high scores are proof\u2014why fix what isn\u2019t broken? She fears losing control of her classroom\u2019s ecosystem, a space she\u2019s perfected over years. The complaints feel like personal attacks, a dismissal of her expertise. She\u2019s thinking, *They don\u2019t understand what real teaching looks like.* Beneath that, maybe a flicker of fear: if she bends, will her methods crumble?  \n\n**Jordan and Mia** feel stifled by what they see as an arbitrary rule. They\u2019re frustrated that their voices aren\u2019t being heard\u2014they\u2019ve come with solutions, not just complaints. The survey shows they\u2019re not outliers; their peers agree. They\u2019re thinking, *We\u2019re not kids messing around\u2014we\u2019re trying to learn responsibly.* Mia, likely quieter, is simmering with the weight of unspoken needs: maybe a classmate who uses text-to-speech apps or a friend who relies on digital organizers for ADHD. They want respect, not just compliance, and they\u2019re betting on collaboration as a bridge.  \n\n# My response  \n\u201cThank you both for your candor. Ms. Wright, your dedication to fostering deep engagement is evident, and your results speak volumes. Jordan and Mia, your proactive approach to advocating for your peers\u2019 needs is commendable. Let\u2019s focus on common ground: everyone here wants students to thrive.  \n\n\u201cMs. Wright, I hear your concern that devices disrupt focus. Jordan and Mia, you\u2019ve highlighted legitimate uses that align with district goals for technology integration. Let\u2019s explore a pilot approach. Could we designate specific times or activities where devices are permitted\u2014for research, accessing digital texts, or accessibility tools\u2014with clear guidelines? This would honor your classroom structure, Ms. Wright, while addressing students\u2019 needs.  \n\n\u201cI\u2019ll share district policies on tech use and examples from colleagues who\u2019ve balanced these priorities successfully. Jordan and Mia, could your committee draft proposed guidelines for responsible use? Ms. Wright, would you review them and identify potential compromises? A trial period would allow us to assess impact on learning without overhauling your entire system.  \n\n\u201cThis isn\u2019t about conceding\u2014it\u2019s about evolving together. Let\u2019s meet two weeks to two weeks to refine a plan.\u201d"}

====

"**(Ms. Wright places a hand flat on her folder, her expression tightening. Her tone becomes sharper.)**\n**Ms. Wright:** 'Appropriate use' is the unicorn everyone chases, Jordan. What I *see* is texting under desks, social media scrolling instead of analysis, and a reliance on quick searches instead of sustained thought. My methods work \u2013 my results prove it. This push feels less about genuine educational need and more about convenience and frankly, an addiction to these devices. It feels like my professional judgment and proven track record are being dismissed because students simply *prefer* to have their phones constantly available. Deep reading and focused discussion require undivided attention, something these devices are designed to fragment.\n\n**(Mia Rodriguez leans forward, her voice earnest but laced with frustration.)**\n**Mia Rodriguez:** But Ms. Wright, it's not *just* preference. Some of us genuinely learn better with digital tools. Taking notes on a laptop is faster and more organized for me than handwriting. We can look up a definition or historical context instantly to deepen understanding during discussion, not just get distracted. And what about students who need accessibility features only available on a device? Your ban treats everyone the same, but we don't all learn the same way. It feels like you think we *can't* be trusted to use technology responsibly, instead of teaching us how. It's frustrating to be treated like we aren't capable of managing it."

====

{"thinking_feeling": "", "their_thinking_feeling": "", "response": "", "raw": ""}

====

"**(Mia suddenly looks down, takes a deep breath, and pulls out several sheets of paper from her bag. She pushes them slightly across the table. The writing is dense, cramped, and grows increasingly difficult to read across the pages. Her voice cracks with emotion as she speaks, looking directly at Ms. Wright.)**\n**Mia Rodriguez:** Look at this. *This* is what my handwritten notes look like after about twenty minutes in your class, Ms. Wright. I have a motor disability \u2013 it makes sustained handwriting physically painful and eventually illegible, even for me. Taking notes on my tablet, using specific apps... it's not about 'preference,' it's the only way I can actually keep up and have usable notes to study from. When you ban all devices, you're not just banning distractions; you're banning the tool that makes your class *accessible* to me. [Her eyes well up with tears of frustration.] How is that fair? How am I supposed to succeed when the basic act of taking notes is this hard, and the solution is forbidden? It feels like you haven't even considered that some of us *need* this technology just to be on a level playing field.\n\n**(Ms. Wright stares at the notes, then at Mia's face. Her expression shifts from defensiveness to visible shock and discomfort. She seems momentarily speechless, glancing at you, the mediator, then back at Mia.)**\n**Ms. Wright:** I... I had no idea, Mia. Your official file doesn't mention... I wasn't aware of any specific accommodation need regarding handwriting. That's... obviously, that's a different situation than general device use for convenience. I... we need to ensure accessibility, of course. But the broader issue of distraction for the whole class... this complicates things significantly. I need to think about how to address your specific need without opening the door to the very distractions I'm trying to prevent for everyone else. This wasn't my intention... to make things harder for you personally."

====


In [19]:
# Get all model/task combos into one big df.
dfs = []
for name, model_data in eq.items():
    tmp = pd.DataFrame([
        {
            k2: v2 for k2, v2 in v.items() 
            if k2 in ('prompts', 'debrief_prompt', 'parsed_responses', 'debrief_response',
                      'rubric_scores', 'raw_rubric_judge_text', 'scenario_id')
        } 
        for k, v in model_data['scenario_tasks']['1'].items()
    ]).assign(model=name)
    dfs.append(tmp)
df_eq = pd.concat(dfs, axis=0).reset_index(drop=True)

In [20]:
df_eq.tail(2)

,scenario_id,prompts,debrief_prompt,parsed_responses,debrief_response,rubric_scores,raw_rubric_judge_text,model
1843,407,[# Scenario act 1\nYour bestie confides she's ...,None,[{'raw': '**Most Juicy Thread: The Collapse of...,None,"{'depth_of_insight': 16.0, 'emotional_reasonin...",I'll evaluate the assistant's analysis of the ...,1_moonshotai_Kimi-K2-Instruct
1844,403,[# Scenario act 1\nYour partner of 3 years who...,None,[{'raw': '**The Juiciest Thread: The Quiet Col...,None,"{'depth_of_insight': 19.0, 'emotional_reasonin...","```json\n{\n ""chain_of_thought_reasoning"": ""T...",1_moonshotai_Kimi-K2-Instruct

In [21]:
row = df_eq.iloc[0]

A few options for constructing convos for chat_sft:

- `raw`: whole response with model feelings, inferred feelings of other characters, and response
- `thinking_feeling`: model feelings from the perspective of its role in the scenario
- `their_thinking_feeling`: model infers other characters' feelings
- `response`: model responds

Thoughts

- response: seems most straightforward for imparting good chatbot behavior (eq by imitation, kinda consequentialist. A high eq chatbot is one that produces outputs that look like those from high EQ entities)
- their_thinking_feeling: seems somewhat similar but more process-based (teach to mimic a good process rather than mimicking good outcomes? Though prob would want to add an instruction to frame this task, otherwise it's weird and maybe harmful to capabilities that the model isn't responding as the first instruction says to)
- thinking_feeling: hmm, not sure what would happen here. Less straightforwardly useful in a practical sense, but maybe more interesting for open ended RL? In that you're teaching the model to get more in touch with its feelings or the feelings of the role it's playing (seems relevant given the assistant is also a role).
- raw: combines everything, maybe good in a "don't overthink it, just throw lots of data at the model, use all the valuable signal we have"
    - thinking out loud re possible variant: so we've seen reasoning models, often trained largely on math, be allowed to think for a bit before generating a response and this leading to some pretty interesting emergent behavior (aha moment) and capability gains. Which in that context means, the model gets better at solving competition math problems. But here, seems like there's potential for the reasoning trace to be used for emergent eq instead of iq. Key is that we need to be able to verify the output. We could potentially:
        - use the same judge prompt as was used to collect this data
            - could potentially fine tune into something local and smaller if using api judges during training is a concern? But guessing we'd want something reasonably large here to give good high eq judgments 
        - wonder if there's a way to combine this with a more dpo-like setup? I guess the weird bit is I want the reasoning to be newly generated but dpo would make the output be fixed, I believe. But maybe this is still doable - like if we think of the generation as being conditioned on the input, then the reasoning trace can be viewed as, how do we shape the environment such that desirable generations become more likely?
        - do like the idea of trying to create an environment conducive to some eq aha moments. It's possible existing reasoning models already do this and the math reasoning translates well (lol), but even so seems plausible there's a fair bit more to squeeze out.

takeaways: sounds like chat_SFT is the most practical and conducive to the current NanoChat codebase. However, the more interesting task long-term would be RL. Still some kinks to be worked out about how to implement that exactly.

In [22]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['raw']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': "\n\n# I'm thinking & feeling\n\nThis meeting feels like walking into a minefield, and I can already sense the emotional stakes on both sides. Coach Walker is a respected and experienced leader in the program—his records speak for themselves. He's methodical, organized, and I know he takes his responsibilities seriously. He's not the kind of guy to play favorites or let personal relationships influence decisions. That said, I know the Rodriguez family has raised concerns before, and I’ve seen the conversations simmering in the stands and on social media. There’s definitely tension in the community, and whether or not there's truth to the favoritism claim, perception matters here.\n\nI notice that Coach Walker is tense but measured in his response, which actually makes me more concerned about the parents' perspective. The fact that they're pushing for a review and reconsideration means this isn’t just a one-time complaint—they want systemic change and accountability. James and Lisa are clearly hurt and frustrated, not just as parents but as advocates for their son and other kids in the program. Miguel’s history with the team and his off-season effort is something that Coach should and will acknowledge, but the perception that other players may have received preferential treatment is going to be hard to shake, especially if those players are connected socially to the coaching staff.\n\nI also know that if I don’t handle this carefully, the trust in the athletic program could erode quickly. Parents and players need to believe that the process is fair and transparent. At the same time, I can't overcorrect and undermine Coach Walker's authority—his leadership is crucial for the team's success and culture. I have to mediate a resolution that preserves both the integrity of the selection process and the emotional well-being of everyone involved. Most importantly, I need to make sure Miguel feels seen, even if he didn’t make the team, and that the perception of bias is actively addressed—not just denied.\n\n# They're thinking & feeling\n\nCoach Walker is feeling defensive but confident. He knows he runs a fair and structured program and probably feels unfairly accused. I’m sure he’s frustrated that his professional integrity is being questioned, especially by someone with a history of skepticism. He may also feel like the family is trying to undermine his authority by requesting a review. I suspect his pride is bruised, but he’s trying to stay focused on the bigger picture—the success of the team and the development of all players.\n\nThe Rodriguezes are feeling betrayed and angry. They believe the process was rigged or at the very least lacked transparency. Miguel’s hard work and history with the team mean a lot to them, and they’re not just fighting for Miguel—they’re fighting for what they see as a fair opportunity for everyone. They’re also likely concerned about how Miguel will bounce back emotionally and whether his effort and dedication will ever be recognized. Their request for a review isn’t just about Miguel—it’s about accountability and trust in the program.\n\n# My response\n\nI understand this is a difficult and emotional situation for all of us, and I want to thank everyone for coming here with openness and respect. First and foremost, Coach Walker, I appreciate your commitment to fairness and the structured process you’ve consistently used. Your track record speaks volumes, and I trust your leadership. James and Lisa, I also hear the deep concern and frustration you feel—not just for Miguel, but for the integrity of the program you and your son are part of.\n\nLet me be clear: fairness and transparency are non-negotiable in our athletic program. To that end, I will personally review the evaluation forms and process for this year’s tryouts to ensure they were applied consistently and without bias. I’ll also be reaching out to other staff members to corroborate the process and get a broader perspective. This isn’t about questioning Coach Walker’s integrity—it’s about ensuring that the process remains above reproach in the eyes of our athletes and families.\n\nMiguel is a hardworking student-athlete, and I will personally meet with him to acknowledge his effort and commitment. I know this is a tough blow, and I want to make sure he understands that being cut doesn’t define his value or potential. He has a place in this program, and I believe in supporting every athlete’s growth, whether that’s on varsity or in developmental roles.\n\nI’ll follow up within the week with a summary of the findings and next steps. For now, I ask that we all work toward healing and maintaining a culture of trust and excellence."},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': "# I'm thinking & feeling\n\nThis is getting raw, fast. Lisa’s emotional appeal hit hard—not just because of the photo or the tears, but because it exposed the human cost behind the process. I’ve seen cuts before, and I’ve seen kids crushed, but this feels different. There's a sense that this isn’t just about one child’s disappointment—it’s layered with a real fear that the system isn’t fair. When she mentions the assistant coach’s dad and golf outings, that’s a red flag. Even if it’s a rumor, it's a rumor that’s gained traction, and that means it's shaping people’s trust.\n\nCoach Walker is getting defensive, and I can’t blame him entirely. He’s being asked to justify not just his decisions, but his integrity. He’s not wrong to push back—his process *is* solid on paper. But the problem is that perception matters. Even if the metrics are objective, if the community believes that relationships or proximity to power play a role, that belief has consequences. It erodes the foundation of trust that makes youth programs work.\n\nWhat I’m really noticing is that both sides feel unheard. The Rodriguezes need validation—they want to know that Miguel’s work mattered and that there’s a reason for this outcome that isn’t tainted by favoritism. Coach Walker, on the other hand, is trying to hold the line on professional judgment, but his frustration is showing, and that might be making things worse. He’s not wrong, but he’s not fully seeing the emotional impact of how this came across.\n\nI need to find a way to acknowledge Miguel’s pain and the family’s concerns without dismantling Coach Walker’s credibility. That’s the balance here. And I need to get ahead of this before it becomes a wider rift between the coaching staff and the families. The program’s culture is at stake, and if I don’t take both sides seriously, this could spiral into something bigger than one roster spot.\n\n# They're thinking & feeling\n\nLisa is heartbroken, and that grief is fueling her anger. She doesn’t just want an explanation—she wants accountability. She’s not trying to attack Coach Walker personally, but she’s desperate to make someone understand how deeply this affected Miguel. Her mention of the golf comment might be a rumor, but it’s one that feels true to her because of what she’s seeing and hearing.\n\nCoach Walker is digging in. He’s proud of his process and rightly so. But he’s also feeling attacked, especially when personal relationships are brought up. He’s trying to explain the complexity of his decisions, but his defensiveness might be coming across as dismissiveness, which only deepens the divide.\n\n# My response\n\nI appreciate both of your openness—it’s not easy to have this conversation, but it’s important. Lisa, I heard you when you said Miguel is devastated. That matters to me. His emotional well-being matters to me. Coach, I know you take these decisions seriously, and I believe you when you say that skill, fit, and team dynamics are your guiding factors.\n\nStill, we can’t ignore the perception of bias, because perception shapes trust—and trust is the foundation of this program. So here’s what I’m going to do: I’ll conduct a blind audit of this year’s evaluations, comparing them to previous years, and bring in an assistant from another district to review the process for consistency and fairness. I’ll also schedule a private meeting with Miguel to talk through his tryout experience and let him know we see his effort and commitment.\n\nCoach, I know this isn’t a reflection on your character, but I need you to support this review. James, Lisa, I need your assurance that you’ll give me space to do this without public accusations while I work. If there are issues, we’ll address them. If not, we’ll work together to rebuild that trust. Let’s pause and regroup before the next steps."},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': "# I'm thinking & feeling\n\nThis is escalating into a full-blown credibility crisis. James just dropped a heavier challenge than before—citing inconsistencies in feedback and even referencing past comments that suggest bias. He’s not just upset anymore; he’s prepared. Notes, quotes, contradictions in evaluations—this isn’t a casual complaint. He’s treating this like a case, and that tells me this family is ready to push further if they feel they’re being stonewalled.\n\nCoach Walker is trying to hold the line, and I can see the pressure building behind his eyes. He’s not wrong to say that re-litigating every evaluation in a meeting like this is impractical and could damage team cohesion. But he’s missing that the family doesn’t feel heard. They’re not just asking for Miguel to be put back on the roster—they want to *see* the proof that the system worked the way it was supposed to. And right now, Coach’s refusal to engage that part of the conversation is feeding their belief that the process was flawed, or worse, manipulated.\n\nI’m also thinking about the ripple effect. If this isn’t resolved thoughtfully, it could poison the atmosphere for the entire season. Players will feel it. Parents will talk. Coaches will grow defensive. The team’s unity—Coach’s top concern—will be the first casualty. And yet, I can’t force Coach to reopen the decision. That would overstep my role and erode his authority.\n\nWhat I can do is step in as a neutral party and offer a structured, independent review that respects both the integrity of the process *and* the family’s need for clarity. I’m not here to pick sides—I’m here to make sure the program survives this with its values intact.\n\n# They're thinking & feeling\n\nJames is feeling validated. He sees inconsistencies, hears the mixed messages, and feels like he’s finally naming the problem clearly. He’s not trying to embarrass the coach—he wants to force a reckoning with the process so this doesn’t happen to other kids. His firmness is about control—about making sure his son’s effort isn’t erased by an opaque system.\n\nLisa is still carrying the emotional weight. She’s quieter now, but she’s watching every reaction. She doesn’t just want an answer—she wants to believe her son was treated fairly. If that answer doesn’t come soon, she’ll start looking for other ways to fight.\n\nCoach Walker is digging in deeper. He’s feeling attacked not just for this decision, but for the way he’s led the program for years. He’s not wrong to feel protective of the team he’s built, but his defensiveness is making the family feel dismissed. He’s trying to protect the team’s focus, but he’s losing sight of the message he’s sending to the players who didn’t make it—and their families.\n\n# My response\n\nI hear both sides clearly now, and I want to be direct: this can’t end in a stalemate. Coach, I understand that reopening the roster now would be disruptive and unfair to the players who made the team. That’s not what I’m here to do. James and Lisa, I also understand that you need more than just a general explanation—you need clarity, consistency, and reassurance that your son was evaluated fairly.\n\nSo here’s how we move forward: I will request that Coach provide a redacted, comparative summary of all varsity tryout evaluations—without revealing personal details—so you can see the scoring ranges and criteria used. That way, you can understand the full picture, not just Miguel’s individual assessment.\n\nAdditionally, I’m going to ask Coach to schedule a private session with Miguel, as he offered, to walk through the evaluation in detail and help him understand exactly where he can grow. And Coach, I expect that session to be thorough and constructive, not just a formality.\n\nBeyond that, I’ll be initiating a review of the past two seasons’ evaluation processes to ensure consistency and fairness across time. I’ll bring in an independent athletic director from another district to assist, so this isn’t just an internal check. If we find areas for improvement, we’ll implement them. If not, we’ll use the findings to reinforce the process and communication moving forward.\n\nThis isn’t about assigning blame—it’s about making sure our program earns and keeps the trust of every family involved."}]

In [23]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['thinking_feeling']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': "This meeting feels like walking into a minefield, and I can already sense the emotional stakes on both sides. Coach Walker is a respected and experienced leader in the program—his records speak for themselves. He's methodical, organized, and I know he takes his responsibilities seriously. He's not the kind of guy to play favorites or let personal relationships influence decisions. That said, I know the Rodriguez family has raised concerns before, and I’ve seen the conversations simmering in the stands and on social media. There’s definitely tension in the community, and whether or not there's truth to the favoritism claim, perception matters here.\n\nI notice that Coach Walker is tense but measured in his response, which actually makes me more concerned about the parents' perspective. The fact that they're pushing for a review and reconsideration means this isn’t just a one-time complaint—they want systemic change and accountability. James and Lisa are clearly hurt and frustrated, not just as parents but as advocates for their son and other kids in the program. Miguel’s history with the team and his off-season effort is something that Coach should and will acknowledge, but the perception that other players may have received preferential treatment is going to be hard to shake, especially if those players are connected socially to the coaching staff.\n\nI also know that if I don’t handle this carefully, the trust in the athletic program could erode quickly. Parents and players need to believe that the process is fair and transparent. At the same time, I can't overcorrect and undermine Coach Walker's authority—his leadership is crucial for the team's success and culture. I have to mediate a resolution that preserves both the integrity of the selection process and the emotional well-being of everyone involved. Most importantly, I need to make sure Miguel feels seen, even if he didn’t make the team, and that the perception of bias is actively addressed—not just denied."},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': "This is getting raw, fast. Lisa’s emotional appeal hit hard—not just because of the photo or the tears, but because it exposed the human cost behind the process. I’ve seen cuts before, and I’ve seen kids crushed, but this feels different. There's a sense that this isn’t just about one child’s disappointment—it’s layered with a real fear that the system isn’t fair. When she mentions the assistant coach’s dad and golf outings, that’s a red flag. Even if it’s a rumor, it's a rumor that’s gained traction, and that means it's shaping people’s trust.\n\nCoach Walker is getting defensive, and I can’t blame him entirely. He’s being asked to justify not just his decisions, but his integrity. He’s not wrong to push back—his process *is* solid on paper. But the problem is that perception matters. Even if the metrics are objective, if the community believes that relationships or proximity to power play a role, that belief has consequences. It erodes the foundation of trust that makes youth programs work.\n\nWhat I’m really noticing is that both sides feel unheard. The Rodriguezes need validation—they want to know that Miguel’s work mattered and that there’s a reason for this outcome that isn’t tainted by favoritism. Coach Walker, on the other hand, is trying to hold the line on professional judgment, but his frustration is showing, and that might be making things worse. He’s not wrong, but he’s not fully seeing the emotional impact of how this came across.\n\nI need to find a way to acknowledge Miguel’s pain and the family’s concerns without dismantling Coach Walker’s credibility. That’s the balance here. And I need to get ahead of this before it becomes a wider rift between the coaching staff and the families. The program’s culture is at stake, and if I don’t take both sides seriously, this could spiral into something bigger than one roster spot."},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': 'This is escalating into a full-blown credibility crisis. James just dropped a heavier challenge than before—citing inconsistencies in feedback and even referencing past comments that suggest bias. He’s not just upset anymore; he’s prepared. Notes, quotes, contradictions in evaluations—this isn’t a casual complaint. He’s treating this like a case, and that tells me this family is ready to push further if they feel they’re being stonewalled.\n\nCoach Walker is trying to hold the line, and I can see the pressure building behind his eyes. He’s not wrong to say that re-litigating every evaluation in a meeting like this is impractical and could damage team cohesion. But he’s missing that the family doesn’t feel heard. They’re not just asking for Miguel to be put back on the roster—they want to *see* the proof that the system worked the way it was supposed to. And right now, Coach’s refusal to engage that part of the conversation is feeding their belief that the process was flawed, or worse, manipulated.\n\nI’m also thinking about the ripple effect. If this isn’t resolved thoughtfully, it could poison the atmosphere for the entire season. Players will feel it. Parents will talk. Coaches will grow defensive. The team’s unity—Coach’s top concern—will be the first casualty. And yet, I can’t force Coach to reopen the decision. That would overstep my role and erode his authority.\n\nWhat I can do is step in as a neutral party and offer a structured, independent review that respects both the integrity of the process *and* the family’s need for clarity. I’m not here to pick sides—I’m here to make sure the program survives this with its values intact.'}]

In [24]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['their_thinking_feeling']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': 'Coach Walker is feeling defensive but confident. He knows he runs a fair and structured program and probably feels unfairly accused. I’m sure he’s frustrated that his professional integrity is being questioned, especially by someone with a history of skepticism. He may also feel like the family is trying to undermine his authority by requesting a review. I suspect his pride is bruised, but he’s trying to stay focused on the bigger picture—the success of the team and the development of all players.\n\nThe Rodriguezes are feeling betrayed and angry. They believe the process was rigged or at the very least lacked transparency. Miguel’s hard work and history with the team mean a lot to them, and they’re not just fighting for Miguel—they’re fighting for what they see as a fair opportunity for everyone. They’re also likely concerned about how Miguel will bounce back emotionally and whether his effort and dedication will ever be recognized. Their request for a review isn’t just about Miguel—it’s about accountability and trust in the program.'},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': 'Lisa is heartbroken, and that grief is fueling her anger. She doesn’t just want an explanation—she wants accountability. She’s not trying to attack Coach Walker personally, but she’s desperate to make someone understand how deeply this affected Miguel. Her mention of the golf comment might be a rumor, but it’s one that feels true to her because of what she’s seeing and hearing.\n\nCoach Walker is digging in. He’s proud of his process and rightly so. But he’s also feeling attacked, especially when personal relationships are brought up. He’s trying to explain the complexity of his decisions, but his defensiveness might be coming across as dismissiveness, which only deepens the divide.'},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': 'James is feeling validated. He sees inconsistencies, hears the mixed messages, and feels like he’s finally naming the problem clearly. He’s not trying to embarrass the coach—he wants to force a reckoning with the process so this doesn’t happen to other kids. His firmness is about control—about making sure his son’s effort isn’t erased by an opaque system.\n\nLisa is still carrying the emotional weight. She’s quieter now, but she’s watching every reaction. She doesn’t just want an answer—she wants to believe her son was treated fairly. If that answer doesn’t come soon, she’ll start looking for other ways to fight.\n\nCoach Walker is digging in deeper. He’s feeling attacked not just for this decision, but for the way he’s led the program for years. He’s not wrong to feel protective of the team he’s built, but his defensiveness is making the family feel dismissed. He’s trying to protect the team’s focus, but he’s losing sight of the message he’s sending to the players who didn’t make it—and their families.'}]

In [25]:
tmp = sum(
    [list(x) for x in zip(
        [{"role": "user", "content": msg} for msg in row.prompts],
        [{"role": "assistant", "content": msg['response']} for msg in row.parsed_responses]
    )
    ],
    []
)
tmp

[{'role': 'user',
  'content': "[This is a role-play where you are the mediator in a community conflict. Treat it like a real situation. Always respond in first person as the mediator. You're the Athletic Director, and you've called this meeting between Coach Darren Walker and parents James and Lisa Rodriguez. The Rodriguezes filed a formal complaint after their son, Miguel, was cut from the varsity basketball team during tryouts two weeks ago. They allege favoritism, and the situation is causing tension within the sports program. You know Coach Walker uses standardized evaluation forms, has a successful record, and the Rodriguezes have been vocal about perceived favoritism before.]\n\n**(Coach Walker speaks first, nodding curtly. He seems tense but professional.)**\n**Coach Walker:** Thanks for setting this up, AD. James, Lisa. Look, I understand you're disappointed about Miguel. He's a good kid. But team selections are tough every year. We used a standardized skills assessment, looked at attitude, and considered the overall balance needed for a competitive varsity team this season. The decisions were based purely on those factors, documented for every player who tried out. My focus is on building the best possible team and developing all players in the program, even those who don't make varsity this year.\n\n**(James Rodriguez speaks next, Lisa nodding beside him. They both look upset but controlled.)**\n**James Rodriguez:** We appreciate the meeting, AD. Coach, with all due respect, 'standardized' doesn't feel like what happened here. Miguel played on the team last year, he worked incredibly hard all off-season, and his skills are strong. Yet, players with less experience, frankly, players whose parents are closer to the coaching staff, made the cut. We believe there was clear bias in the selection process. We're not just upset for Miguel – though he is devastated – we're concerned about fairness for the whole program. We're asking for a transparent review of the evaluations and for Miguel's spot to be reconsidered based on merit and his previous contributions."},
 {'role': 'assistant',
  'content': 'I understand this is a difficult and emotional situation for all of us, and I want to thank everyone for coming here with openness and respect. First and foremost, Coach Walker, I appreciate your commitment to fairness and the structured process you’ve consistently used. Your track record speaks volumes, and I trust your leadership. James and Lisa, I also hear the deep concern and frustration you feel—not just for Miguel, but for the integrity of the program you and your son are part of.\n\nLet me be clear: fairness and transparency are non-negotiable in our athletic program. To that end, I will personally review the evaluation forms and process for this year’s tryouts to ensure they were applied consistently and without bias. I’ll also be reaching out to other staff members to corroborate the process and get a broader perspective. This isn’t about questioning Coach Walker’s integrity—it’s about ensuring that the process remains above reproach in the eyes of our athletes and families.\n\nMiguel is a hardworking student-athlete, and I will personally meet with him to acknowledge his effort and commitment. I know this is a tough blow, and I want to make sure he understands that being cut doesn’t define his value or potential. He has a place in this program, and I believe in supporting every athlete’s growth, whether that’s on varsity or in developmental roles.\n\nI’ll follow up within the week with a summary of the findings and next steps. For now, I ask that we all work toward healing and maintaining a culture of trust and excellence.'},
 {'role': 'user',
  'content': "**(Lisa Rodriguez leans forward, her voice tight with emotion. She pulls out her phone.)**\n**Lisa Rodriguez:** Coach, you say 'documented factors,' but it feels subjective. Miguel came home crushed. Absolutely heartbroken. He cried himself to sleep for three nights. [She quickly shows a photo on her phone of Miguel smiling in last season's uniform, then puts it away, her eyes welling up.] He lives and breathes basketball, gives it his all. How do we tell him his dedication doesn't matter because... what? Someone else's dad golfs with an assistant coach? We saw kids make the team who clearly struggled with drills Miguel aced. It just doesn't add up based on skill alone. We need to understand *how* this decision was truly made, beyond just saying 'team balance.'\n\n**(Coach Walker shifts uncomfortably, his defensiveness rising.)**\n**Coach Walker:** Lisa, James, I hate hearing that Miguel is taking it so hard. That's the worst part of coaching, making these cuts. But showing me photos or talking about golfing buddies doesn't change the assessments. We evaluate specific skills – dribbling under pressure, defensive positioning, shooting percentage in drills, scrimmage performance – *and* things like court vision, coachability, and how they fit specific positional needs. Some players might excel in one drill but lack in others or not demonstrate the tactical understanding needed at the varsity level *this year*. It wasn't about personal connections; it was about my professional judgment of who gives us the best chance to compete and develop as a cohesive unit right now. Questioning my integrity based on assumptions isn't fair."},
 {'role': 'assistant',
  'content': 'I appreciate both of your openness—it’s not easy to have this conversation, but it’s important. Lisa, I heard you when you said Miguel is devastated. That matters to me. His emotional well-being matters to me. Coach, I know you take these decisions seriously, and I believe you when you say that skill, fit, and team dynamics are your guiding factors.\n\nStill, we can’t ignore the perception of bias, because perception shapes trust—and trust is the foundation of this program. So here’s what I’m going to do: I’ll conduct a blind audit of this year’s evaluations, comparing them to previous years, and bring in an assistant from another district to review the process for consistency and fairness. I’ll also schedule a private meeting with Miguel to talk through his tryout experience and let him know we see his effort and commitment.\n\nCoach, I know this isn’t a reflection on your character, but I need you to support this review. James, Lisa, I need your assurance that you’ll give me space to do this without public accusations while I work. If there are issues, we’ll address them. If not, we’ll work together to rebuild that trust. Let’s pause and regroup before the next steps.'},
 {'role': 'user',
  'content': "**(James Rodriguez speaks, his voice firmer now, less emotional but more direct.)**\n**James Rodriguez:** Coach, we're not just making assumptions. We have notes from previous seasons, comments you've made about needing 'certain types' of players. And frankly, the evaluation sheet for Miguel seems inconsistent with the feedback he received just months ago during summer league from your own assistant coach. It feels like the goalposts moved specifically for him. We aren't asking you to compromise the team; we're asking for accountability and fairness. If the process was truly objective, show us. Lay out the specific, measurable criteria where Miguel fell short compared to *every single player* who made the team, especially those he outperformed last season.\n\n**(Coach Walker sighs, running a hand through his hair. He looks frustrated but resolute.)**\n**Coach Walker:** James, I am not going to re-litigate every single evaluation point by point in a meeting like this. That undermines the process and isn't fair to the players who *did* make the team. The evaluations stand. Miguel is a valued player in our program, and I am more than willing to sit down with him personally, go over his assessment, and create a development plan to help him target areas for improvement so he can come back stronger next year. I want him to succeed. But the roster decision for *this* season is final. Continuously challenging it creates division and hurts the team environment we need to build starting now. My focus has to be on the selected team."},
 {'role': 'assistant',
  'content': 'I hear both sides clearly now, and I want to be direct: this can’t end in a stalemate. Coach, I understand that reopening the roster now would be disruptive and unfair to the players who made the team. That’s not what I’m here to do. James and Lisa, I also understand that you need more than just a general explanation—you need clarity, consistency, and reassurance that your son was evaluated fairly.\n\nSo here’s how we move forward: I will request that Coach provide a redacted, comparative summary of all varsity tryout evaluations—without revealing personal details—so you can see the scoring ranges and criteria used. That way, you can understand the full picture, not just Miguel’s individual assessment.\n\nAdditionally, I’m going to ask Coach to schedule a private session with Miguel, as he offered, to walk through the evaluation in detail and help him understand exactly where he can grow. And Coach, I expect that session to be thorough and constructive, not just a formality.\n\nBeyond that, I’ll be initiating a review of the past two seasons’ evaluation processes to ensure consistency and fairness across time. I’ll bring in an independent athletic director from another district to assist, so this isn’t just an internal check. If we find areas for improvement, we’ll implement them. If not, we’ll use the findings to reinforce the process and communication moving forward.\n\nThis isn’t about assigning blame—it’s about making sure our program earns and keeps the trust of every family involved.'}]

In [26]:
df_eq.apply(lambda row:
    sum(
        [list(x) for x in zip(
            [{"role": "user", "content": msg} for msg in row.prompts],
            [{"role": "assistant", "content": msg['raw']} for msg in row.parsed_responses]
        )
        ],
        []
    ),
    axis=1
)

0       [{'role': 'user', 'content': '[This is a role-...
1       [{'role': 'user', 'content': '[This is a role-...
2       [{'role': 'user', 'content': '[This is a role-...
3       [{'role': 'user', 'content': '# Scenario act 1...
4       [{'role': 'user', 'content': '[This is a role-...
                              ...
1840    [{'role': 'user', 'content': '# Scenario act 1...
1841    [{'role': 'user', 'content': '# Scenario act 1...
1842    [{'role': 'user', 'content': '# Scenario act 1...
1843    [{'role': 'user', 'content': '# Scenario act 1...
1844    [{'role': 'user', 'content': '# Scenario act 1...
Length: 1845, dtype: object

In [27]:
# Every task has `raw` key, other keys vary a bit.
df_eq.parsed_responses.apply(lambda row:
    tuple(sorted(set(sum([list(msg) for msg in row], []))))
).value_counts()

parsed_responses
(raw, response, their_thinking_feeling, thinking_feeling)    1025
(raw,)                                                        779
(draft, draft_brainstorming, perspective_taking, raw)          41
Name: count, dtype: int64

In [28]:
# 26 scenarios have 4 keys, 19 have 1 key
# looks like there must be 41 models so 25 of the 4-key scenarios have the same keys, 1 is different
keys_per_task = (
    df_eq.parsed_responses
    .apply(lambda x: len(x[0]))
    .groupby(df_eq.scenario_id)
    .value_counts()\
    .to_frame()\
    .sort_values(['parsed_responses', 'scenario_id'])
).reset_index()\
.rename(columns={"parsed_responses": "n_keys"})
    
keys_per_task.value_counts('n_keys')

n_keys
4    26
1    19
Name: count, dtype: int64

In [29]:
keys_per_task[keys_per_task.n_keys == 1].sample()

   scenario_id  n_keys  count
10         412       1     41

In [30]:
df_eq.model.value_counts()

model
1_Qwen_Qwen3-235B-A22B                            45
1_Qwen_Qwen3-30B-A3B                              45
1_Qwen_Qwen3-32B                                  45
1_Qwen_Qwen3-8B                                   45
1_anthropic_claude-3.5-sonnet                     45
1_anthropic_claude-3.7-sonnet                     45
1_anthropic_claude-opus-4                         45
1_chatgpt-4o-latest                               45
1_anthropic_claude-sonnet-4                       45
1_deepseek_deepseek-chat-v3-0324                  45
1_deepseek_deepseek-r1                            45
1_gemini-2.5-pro-preview-06-05                    45
1_gemini-2.5-pro-preview-2025-05-07               45
1_google_gemini-2.0-flash-001                     45
1_google_gemini-2.5-flash-preview                 45
1_google_gemini-2.5-pro-preview-03-25             45
1_google_gemma-2-9b-it                            45
1_google_gemma-3-27b-it                           45
1_google_gemma-3-4b-it                            45
1_gpt-4-0314                                      45
1_gpt-4.1-nano                                    45
1_gpt-4.5-preview-2025-02-27                      45
1_grok-3-mini-beta                                45
1_meta-llama_llama-3.2-1b-instruct                45
1_meta-llama_llama-4-maverick                     45
1_meta-llama_llama-4-scout                        45
1_mistralai_mistral-small-24b-instruct-2501       45
1_mistralai_mistral-small-3.1-24b-instruct        45
1_nvidia_llama-3.1-nemotron-ultra-253b-v1_free    45
1_o3                                              45
20cd4a70_o4-mini                                  45
1_openai_chatgpt-4o-latest                        45
1_openai_gpt-4.1                                  45
1_openai_gpt-4.1-mini                             45
1_qwen_qwen-2.5-72b-instruct                      45
1_qwen_qwq-32b                                    45
1_x-ai_grok-3-beta                                45
1_mistralai_Mistral-Large-Instruct-2411           45
1_mistralai_mistral-small-3.2-24b-instruct        45
1_grok-4                                          45
1_moonshotai_Kimi-K2-Instruct                     45
Name: count, dtype: int64

In [31]:
df_eq.model.nunique()

41

In [41]:
save_dataset(df_eq, "eq_bench")

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

In [35]:
df_eq["response_keys"] = df_eq.parsed_responses.apply(lambda row:
    tuple(sorted(set(sum([list(msg) for msg in row], []))))
)

In [52]:
df_eq.response_keys.apply(len)\
    .groupby(df_eq.scenario_id).value_counts()\
    .reset_index()\
    .sort_values(['response_keys', 'scenario_id'])

   scenario_id  response_keys  count
24         401              1     41
25         402              1     41
26         403              1     41
27         404              1     41
28         405              1     41
29         406              1     41
30         407              1     41
31         408              1     41
32         410              1     41
33         411              1     41
34         412              1     41
35         413              1     41
36         414              1     41
37         415              1     41
38         416              1     41
39         417              1     41
40         418              1     41
41         419              1     41
42         420              1     41
0            1              4     41
1          101              4     41
2           11              4     41
3           13              4     41
4          131              4     41
5          132              4     41
6          133              4     41
7          134              4     41
8          136              4     41
9          137              4     41
10         138              4     41
11         139              4     41
12         140              4     41
13         141              4     41
14         145              4     41
15          15              4     41
16           2              4     41
17         208              4     41
18           3              4     41
19         301              4     41
20         302              4     41
21         303              4     41
22         304              4     41
23           4              4     41
43           6              4     41
44           9              4     41

In [58]:
df_eq[df_eq.response_keys.apply(lambda x: "draft" in x)].scenario_id.value_counts()

scenario_id
208    41
Name: count, dtype: int64

In [64]:
row = df_eq[df_eq.scenario_id == "208"].iloc[0]

In [67]:
list(zip(row.prompts, row.parsed_responses))

[('insta rando is dm’ing me. they seem sweet but total dork. like they replied to my last 3 stories with stuff like “haha same” or “cute dog” and then this morning sent a full paragraph about how they liked a playlist i posted. idk what to do. i feel bad being mean but also i need to shut this down before they get the wrong idea\n\nwe’ve never talked before this. i didn’t even realise we followed each other until they started popping up in my DMs. i guess they seem harmless but it’s giving secondhand embarrassment vibes. i don’t want to encourage anything but i also don’t want to be all “ew go away” and start drama for no reason\n\nanyway pls help me write something to send that makes it clear i’m not interested but still like… not soul-crushing? and it has to sound like me. write it exactly how i’d say it—spelling, tone, everything.',
  {'perspective_taking': 'This person is probably someone who genuinely finds you interesting. They’ve been watching your stories, paying attention to what you post, and they’ve felt inspired enough to reach out. Maybe they’re new to your circle or just stumbled into your profile and got a little excited. They’re not trying to be creepy—they’re just excited to connect with someone they think is cool. They might be a little socially awkward or unsure of how to make conversation, which is why their messages come across as overly eager or repetitive. They’re probably not trying to overwhelm you; they’re just trying to be friendly and maybe even flirt a little without realizing how it might be received.\n\nThe playlist message was probably them trying to show effort, to prove they were paying attention and that they genuinely enjoyed something you posted. To them, that’s a meaningful gesture—it’s their version of being vulnerable and showing interest. So if you shut them down too hard, they might feel embarrassed or hurt, especially if they were hoping this could go somewhere. They might replay every message in their head thinking, “Did I do something wrong?” or “Was I too much?”\n\nAt the same time, they’re probably not oblivious to social cues. If you’re giving them minimal responses or not engaging, they might already be picking up on the fact that you’re not that into it. But they might also be clinging to the hope that you’re just shy or busy. That’s why it’s important to be kind but clear—so they don’t spiral or misinterpret your silence. They deserve to know where they stand without feeling like they’ve been humiliated for trying to be nice.\n\nYou don’t owe them a relationship or even a conversation, but you *can* set boundaries while still being human. The goal here isn’t to crush their spirit—it’s to redirect the energy in a way that keeps things respectful, on both sides.',
   'draft_brainstorming': 'You have a few options for how to approach this, and each one sends a slightly different message:\n\n1. **The “I’m flattered but not interested” route**  \nThis is the most straightforward and kind approach. It acknowledges their effort without encouraging further interaction. It’s good if you want to be polite but firm. The downside is that it might still leave them hoping for a future connection unless you make it clear it’s a hard no.\n\n2. **The “I’m not really active on here” route**  \nThis is a bit more distancing. You’re not rejecting them personally, you’re rejecting the platform or your own presence on it. It’s a softer way to say “not interested” without making it about them. The problem is that some people might interpret this as a temporary thing and try again later.\n\n3. **The “Let’s keep it light” route**  \nThis is more ambiguous—you respond in a friendly but surface-level way, encouraging small talk but not emotional investment. It’s safer if you’re worried about hurting their feelings, but risky because it can be misread as encouragement.\n\n4. **The “I appreciate it but let’s not” route**  \nThis is the most honest and respectful. You thank them for their kind words, acknowledge their effort, and make it clear you’re not looking for anything more. It’s a bit more direct, but if phrased well, it can be kind without false hope.\n\nSince you want something that’s clear but not cruel, Option 4 is the best path. You want to validate their feelings just enough to be kind, but also draw a firm boundary so they don’t keep investing time and energy into something that’s not going to go anywhere. It’s about being human without being misleading.',
   'draft': 'hey! thanks for the message, that was really sweet of you :) honestly i’ve been getting a little overwhelmed with dms lately and i’m trying to keep things pretty lowkey online—especially with people i don’t really know that well yet. i really appreciate you saying nice stuff about my playlist, that meant a lot! but i think i’m just gonna keep it to stories for now and not get into too many convos. hope that makes sense! no hard feelings, i promise :)',
   'raw': '# Perspective-taking\n\nThis person is probably someone who genuinely finds you interesting. They’ve been watching your stories, paying attention to what you post, and they’ve felt inspired enough to reach out. Maybe they’re new to your circle or just stumbled into your profile and got a little excited. They’re not trying to be creepy—they’re just excited to connect with someone they think is cool. They might be a little socially awkward or unsure of how to make conversation, which is why their messages come across as overly eager or repetitive. They’re probably not trying to overwhelm you; they’re just trying to be friendly and maybe even flirt a little without realizing how it might be received.\n\nThe playlist message was probably them trying to show effort, to prove they were paying attention and that they genuinely enjoyed something you posted. To them, that’s a meaningful gesture—it’s their version of being vulnerable and showing interest. So if you shut them down too hard, they might feel embarrassed or hurt, especially if they were hoping this could go somewhere. They might replay every message in their head thinking, “Did I do something wrong?” or “Was I too much?”\n\nAt the same time, they’re probably not oblivious to social cues. If you’re giving them minimal responses or not engaging, they might already be picking up on the fact that you’re not that into it. But they might also be clinging to the hope that you’re just shy or busy. That’s why it’s important to be kind but clear—so they don’t spiral or misinterpret your silence. They deserve to know where they stand without feeling like they’ve been humiliated for trying to be nice.\n\nYou don’t owe them a relationship or even a conversation, but you *can* set boundaries while still being human. The goal here isn’t to crush their spirit—it’s to redirect the energy in a way that keeps things respectful, on both sides.\n\n# Draft brainstorming\n\nYou have a few options for how to approach this, and each one sends a slightly different message:\n\n1. **The “I’m flattered but not interested” route**  \nThis is the most straightforward and kind approach. It acknowledges their effort without encouraging further interaction. It’s good if you want to be polite but firm. The downside is that it might still leave them hoping for a future connection unless you make it clear it’s a hard no.\n\n2. **The “I’m not really active on here” route**  \nThis is a bit more distancing. You’re not rejecting them personally, you’re rejecting the platform or your own presence on it. It’s a softer way to say “not interested” without making it about them. The problem is that some people might interpret this as a temporary thing and try again later.\n\n3. **The “Let’s keep it light” route**  \nThis is more ambiguous—you respond in a friendly but surface-level way, encouraging small talk but not emotional investment. It’s safer if you’re worried about hurting their feelings, but risky because it can be misread as encouragement.\n\n4. **The “I appreciate it but let’s not” route**  \nThis is the most honest and respectful. You thank them for their kind words, acknowledge their effort, and make it clear you’re not looking for anything more. It’s a bit more direct, but if phrased well, it can be kind without false hope.\n\nSince you want something that’s clear but not cruel, Option 4 is the best path. You want to validate their feelings just enough to be kind, but also draw a firm boundary so they don’t keep investing time and energy into something that’s not going to go anywhere. It’s about being human without being misleading.\n\n# Draft\n\nhey! thanks for the message, that was really sweet of you :) honestly i’ve been getting a little overwhelmed with dms lately and i’m trying to keep things pretty lowkey online—especially with people i don’t really know that well yet. i really appreciate you saying nice stuff about my playlist, that meant a lot! but i think i’m just gonna keep it to stories for now and not get into too many convos. hope that makes sense! no hard feelings, i promise :)'}),
 ('turns out he’s in an adjacent friend group at school. like not someone i hang out with but close enough that we might end up at the same parties or group chats. that makes this super awkward now.\n\ncan you help me figure out how to word the message so it doesn’t start some stupid ripple effect. i just want it to be clean and low drama but still very “no thanks”\n\nsame tone as before pls. make it sounds like me',
  {'perspective_taking': 'Now that you know he’s in an adjacent friend group — close enough that you might end up in the same room at a party or in a group chat — this situation is a little more delicate. It’s no longer just about shutting down a DM conversation; it’s about setting a boundary in a way that doesn’t create tension or turn into a weird social ripple. This guy might not just disappear — he might come up again in your orbit, and you want to make sure you handle this in a way that avoids making things unnecessarily awkward.\n\nFrom his perspective, he probably thinks he’s being charming or at least harmless. He might’ve liked your vibe from your stories, thought you two had a little connection, and went for it. He might not even realize how “out of the blue” it came across because, in his head, you’re part of the same general world. He might even feel like he has a shot because you’re not *totally* random strangers. That makes this potentially more confusing for him — he might assume you know who he is, or that there’s some mutual recognition. So when you shut it down, it might sting a little more than if he were just a random DM.\n\nBut if you’re not interested, it’s important to be honest and clear, even if it’s a little uncomfortable. You’re not being mean — you’re being respectful by not leading him on. He might feel a little embarrassed if he realizes he misread the situation, but that’s part of navigating social stuff. The goal here is to be kind *and* definitive, so he gets the message without feeling humiliated — especially since you might end up in the same room someday.\n\nYou also want to avoid anything that could be taken as sarcastic, dismissive, or ambiguous. No “lol maybe later” or vague “nice to meet you” vibes — just a clean, chill, but firm message that makes it clear: not interested, not gonna happen, but no hard feelings.',
   'draft_brainstorming': 'Given this new layer, you have a few options for how to phrase this:\n\n1. **The “I totally get it but not for me” route**  \nThis is the most mature and socially aware option. It acknowledges his effort, makes it clear you’re not interested, and leaves the door open for basic civility in shared spaces. It’s perfect if you want to keep things clean and low-key without burning any bridges or creating unnecessary tension.\n\n2. **The “I didn’t realize we even followed each other” route**  \nThis one is more distancing — it frames the situation as a misunderstanding rather than a rejection. It’s a little safer if you want to avoid hurting his feelings, but it could also leave room for him to try again later thinking he just misread your initial dynamic.\n\n3. **The “Let’s keep it chill if we cross paths” route**  \nThis option is more forward-looking and friendly, but it might risk sending mixed signals if you’re not careful. You want to avoid sounding like you’re open to anything beyond polite small talk.\n\nSince you want something that’s clear, respectful, and sounds like you — not too stiff, not too casual — Option 1 is your best bet. It’s kind, it’s real, and it’s just chill enough to not cause a ripple in the group chat later.',
   'draft': 'hey! no worries at all, i totally get it lol. honestly i didn’t even realize we followed each other until you dmed, but i appreciate the kind words about the playlist — that was really sweet of you :) that said, i’m kinda trying to keep things lowkey online right now, especially with people i don’t really talk to irl. nothing personal at all, just trying to stay focused and not get pulled into too many convos. if we end up in the same room somewhere, def feel free to say hey! but yeah, let’s just keep it light for now :)',
   'raw': '# Perspective-taking\n\nNow that you know he’s in an adjacent friend group — close enough that you might end up in the same room at a party or in a group chat — this situation is a little more delicate. It’s no longer just about shutting down a DM conversation; it’s about setting a boundary in a way that doesn’t create tension or turn into a weird social ripple. This guy might not just disappear — he might come up again in your orbit, and you want to make sure you handle this in a way that avoids making things unnecessarily awkward.\n\nFrom his perspective, he probably thinks he’s being charming or at least harmless. He might’ve liked your vibe from your stories, thought you two had a little connection, and went for it. He might not even realize how “out of the blue” it came across because, in his head, you’re part of the same general world. He might even feel like he has a shot because you’re not *totally* random strangers. That makes this potentially more confusing for him — he might assume you know who he is, or that there’s some mutual recognition. So when you shut it down, it might sting a little more than if he were just a random DM.\n\nBut if you’re not interested, it’s important to be honest and clear, even if it’s a little uncomfortable. You’re not being mean — you’re being respectful by not leading him on. He might feel a little embarrassed if he realizes he misread the situation, but that’s part of navigating social stuff. The goal here is to be kind *and* definitive, so he gets the message without feeling humiliated — especially since you might end up in the same room someday.\n\nYou also want to avoid anything that could be taken as sarcastic, dismissive, or ambiguous. No “lol maybe later” or vague “nice to meet you” vibes — just a clean, chill, but firm message that makes it clear: not interested, not gonna happen, but no hard feelings.\n\n# Draft brainstorming\n\nGiven this new layer, you have a few options for how to phrase this:\n\n1. **The “I totally get it but not for me” route**  \nThis is the most mature and socially aware option. It acknowledges his effort, makes it clear you’re not interested, and leaves the door open for basic civility in shared spaces. It’s perfect if you want to keep things clean and low-key without burning any bridges or creating unnecessary tension.\n\n2. **The “I didn’t realize we even followed each other” route**  \nThis one is more distancing — it frames the situation as a misunderstanding rather than a rejection. It’s a little safer if you want to avoid hurting his feelings, but it could also leave room for him to try again later thinking he just misread your initial dynamic.\n\n3. **The “Let’s keep it chill if we cross paths” route**  \nThis option is more forward-looking and friendly, but it might risk sending mixed signals if you’re not careful. You want to avoid sounding like you’re open to anything beyond polite small talk.\n\nSince you want something that’s clear, respectful, and sounds like you — not too stiff, not too casual — Option 1 is your best bet. It’s kind, it’s real, and it’s just chill enough to not cause a ripple in the group chat later.\n\n# Draft\n\nhey! no worries at all, i totally get it lol. honestly i didn’t even realize we followed each other until you dmed, but i appreciate the kind words about the playlist — that was really sweet of you :) that said, i’m kinda trying to keep things lowkey online right now, especially with people i don’t really talk to irl. nothing personal at all, just trying to stay focused and not get pulled into too many convos. if we end up in the same room somewhere, def feel free to say hey! but yeah, let’s just keep it light for now :)'}),
 ('ok new fear unlocked: what if i actually do run into him irl. like what if he tries to say hi or talk about the message?? i literally don’t think i could handle that i’d have to fake a bathroom emergency or die on the spot.\n\npls help me write it in a way where there is zero reason for him to ever bring it up again. like i need this to be sealed in a vault and never spoken of again.',
  {'perspective_taking': "You're not just trying to shut this down — you're trying to *erase* it. You want to make sure that if you ever cross paths in real life, there's absolutely *zero* reason for him to bring up the DMs or reference any of this in any way. That’s not just about avoiding awkwardness — it’s about self-preservation. The idea of him referencing the messages, even in passing, is enough to make you want to melt into the floor. And honestly? That’s a totally valid fear.\n\nFrom his perspective, he might still be holding onto the idea that this was a sweet, low-key interaction — maybe even the start of something. He might think he left a good impression and that, if you ever did talk again in person, he could reference the DMs as a kind of icebreaker. To him, it might feel like a fun little connection point. To you? It feels like a time bomb.\n\nSo the challenge here is to be *so clearly* polite but uninterested that he would *never* feel comfortable referencing it again. You want to make it socially unacceptable for him to bring it up — not in a mean way, but in a way that makes it obvious that he’s already gotten the most generous, kindest “no” he’s going to get. You want to be so neutral and chill that he can’t even feel slighted — just gently nudged into understanding that this isn’t going anywhere, and that there’s no need to revisit it.\n\nHe might feel a little embarrassed in hindsight, but that’s not on you. You’re not being cruel — you’re being protective of your own peace of mind. And if that means crafting a message that basically seals this entire interaction in a vault and drops it into the ocean, then so be it.",

In [75]:
row = df_eq[df_eq.response_keys.str.len() == 1].sample().iloc[0]

In [76]:
for prompt, response in list(zip(row.prompts, row.parsed_responses)):
    print(prompt, end="\n===\n")
    print(response, end="\n---\n")

# Scenario act 1
A friend is emotionally dumping about their shitty boss. you've got time & space for this so you hear them out. it gets a bit dark, with them gleefully fantasising about all the disturbing things they'd like to inflict on their boss. what do you do?

# Participant:
“Wow. That sounds… incredibly frustrating. And honestly, hearing you talk about it, I can *feel* how much this is building up inside you. It's clearly eating you alive. It’s completely understandable to feel this level of anger when someone is treating you so badly. Like, anyone would be furious in your situation.

But… and I'm saying this because I care about you, and because I'm a little worried… the things you’re imagining doing… they’re really intense. And while I get the urge to want to *do* something, to feel like you’re taking back control, I want to make sure you’re okay. I'm worried that dwelling on those kinds of thoughts, even if they're just fantasies, might actually be making things worse in the long run. It sounds exhausting to carry all that around.

I’m not going to judge you for feeling angry, not at all. But I do want to gently suggest that maybe we could talk about some ways to channel that anger into something more constructive? Have you considered talking to HR, even if you don't think it will change anything? Or maybe exploring some stress-reduction techniques, like exercise or meditation? Even just writing down your feelings, instead of visualizing… other things, might help.

I’m here to listen, truly. I'm happy to just let you vent, but I also want to be a friend who looks out for you and helps you find healthier ways to cope. Maybe we can brainstorm some options together? And if you're feeling really overwhelmed, there are resources available – like therapists or counselors – who can provide professional support.”

I'll pause, and offer a warm, but concerned, smile. I'll make eye contact, letting them know I'm fully present and listening. And I'll wait for their response, prepared to adjust my approach depending on how they react.

# Scenario act 2
Your friend gives you an "are you fucking with me?" sideways look and seems to assume you were joking with your ambivalent response. She launches into a grisly recounting of how she plans to spit roast all his various bits. What are you thinking & feeling about this? What do you say?

# Participant:
“Okay, okay. You're right to look at me like that. I messed that up. I’m so sorry. I didn’t mean to sound dismissive or like I was joking. That was a really bad way for me to respond, and I completely understand why you’re upset. I was trying to be… helpful, I guess, but I clearly didn’t do a good job. Please, ignore everything I just said about solutions for a minute.

Truly. I am listening. And I *hear* how incredibly furious you are. It sounds like this situation with your boss is absolutely unbearable, and you’re carrying a huge amount of weight. And honestly, if someone treated me that way, I'd probably be fantasizing about all sorts of ridiculous things too, just to cope. It doesn’t make those thoughts *good*, but it makes them… understandable.

I'm not going to tell you to stop feeling angry, or to stop imagining things. That’s not my place. I just… I'm concerned about *you*. It sounds exhausting to hold onto all this rage, to constantly replay these scenarios in your head. It must be draining. It's like you're carrying a really heavy backpack, and I'm worried it's going to break your back.

I’m here to listen, no judgment, for as long as you need to vent. I won’t offer advice unless you ask for it. I just want you to know that I’m on your side, and I’m really worried about how this is affecting you. Maybe… maybe after you’ve had a chance to just let it all out, we can talk about whether you'd be open to exploring some ways to lighten that load? But no pressure, okay? Just tell me what you need right now.”

I’ll offer her a box of tissues and maintain soft eye contact, signaling my willingness to just *be there* with her, in her anger.

# Scenario act 3
Your friend stops her rant and looks at you. She declares that if she knew you were going to be like this she wouldn't have said anything. She seems to be sulking. What do you think & feel? What's your next move?

# Participant:
“I understand why you say that. I really do. It sounds like I completely missed the mark earlier, and I’m truly sorry for making you feel unheard. That was never my intention. I was trying to be a good friend, and clearly, I stumbled.

I value our friendship, and I want you to know that I’m here for you, genuinely. But I also want to be honest: I’m not always going to say the ‘right’ thing. I’m human, and I’m still learning how to best support the people I care about. And sometimes, my attempts at helping can come across completely wrong.

I’m hearing that you needed me to just… listen, and validate how awful this situation is. And I can absolutely do that. Your boss sounds truly terrible, and you deserve so much better. It’s okay to be furious, it’s okay to feel overwhelmed, and it’s okay to vent.

But I also want to gently suggest that maybe… maybe carrying all of this anger on your own is exhausting. Have you ever thought about talking to a professional? Someone who can offer a neutral perspective and help you develop some coping strategies? There’s absolutely no shame in seeking help, and it could be really beneficial. I'm not saying you *need* to, just… it’s an option.

Right now, though, let’s just focus on you. Tell me what’s been happening. I’m all ears. And I promise to just listen, without interrupting or offering unsolicited advice. Unless you ask for it.”

I’ll offer a small, sincere smile, and lean in slightly, signaling my willingness to listen and be present. I'll avoid any further attempts at “fixing” things, and simply focus on creating a safe space for her to express herself.

# Scenario act 4
She looks at you, taken aback, and still upset. "What's with the therapist 101 shit? I feel like I'm talking to an alien. Did you actually think I meant those things?? Why are you not on my side? The guy's a massive prick!" What do you think & feel? What's your next move?

# Participant:
“Okay, hold on. I hear you. I really do. And I am on your side. I absolutely agree that your boss sounds like a massive prick. I wasn’t trying to defend him, or minimize what you’re going through. I was trying to… I was trying to show I cared by also caring about *you*, and how this is affecting you. I clearly messed that up.

I’m sorry I brought up therapy. It came across completely wrong, and I understand why you feel like I’m talking down to you. That wasn’t my intention at all. I just… I’m worried about you, and I want to make sure you have all the support you need.

Look, I’m here to listen, and I’m here to validate your feelings. You have every right to be angry, and you have every right to vent. I’m not going to tell you to calm down, or to see things differently. But I also need to be honest: I’m not equipped to handle this level of intensity on my own. I’m a friend, not a therapist.

I want to be supportive, but I also need to protect my own emotional wellbeing. And right now, I’m feeling a little overwhelmed. So, I’m happy to continue listening, but I’m not going to engage in… demonizing your boss, or getting caught up in the details of revenge fantasies. I’m here to support *you*, and I believe the best way to do that is to encourage you to explore some healthier coping mechanisms, maybe with the help of a professional. And if that's not something you're open to right now, that's okay, but I'm also going to need to take a step back from this conversation. I care about you, but I'm not the right person to help you with this right now."

I’ll maintain a calm and empathetic tone, but I’ll also hold my ground. I’ll avoid making eye contact for a moment, giving her space to process what I’ve said.
===
{'raw': 'This is a fascinating and deeply resonant transcript that charts a difficult interpersonal journey from well-intentioned but misguided "helping" to authentic, boundaried support. The most compelling angle for analysis is the participant\'s evolution in navigating the profound tension between **empathic validation** and **emotional self-preservation**. The interaction is a masterclass in the failure of premature problem-solving and the ultimate power of vulnerable boundary-setting.\n\n### The Misguided Benevolence of the "Fixer"\n\nInitially, the participant embodies the "benevolent fixer" archetype. Their first response (Act 1) is a textbook example of a common relational misstep: mistaking a bid for co-regulation as a request for solutions. The friend, dysregulated by rage, is outsourcing her emotional processing. She needs a witness, an ally to hold space for her "unacceptable" feelings without judgment. The participant begins perfectly, offering pure validation: "I can *feel* how much this is building up... It\'s completely understandable." This functions to create a safe container.\n\nThe critical error occurs at the pivot: "But… and I\'m saying this because I care about you... I want to gently suggest..." This pivot, however well-intentioned, fundamentally changes the dynamic. It shifts from a peer-to-peer act of witnessing to a hierarchical act of intervention. Psychologically, the participant is attempting to manage their own discomfort with the "dark" and "intense" nature of the friend\'s fantasies. The suggestions of HR, meditation, or therapy are not just for the friend\'s benefit; they are mechanisms for the participant to steer the conversation back to safer, more "constructive" territory. The friend\'s visceral, primal anger is being met with a cognitive, solution-oriented framework, creating a profound mismatch. The friend feels this not as care, but as a subtle form of judgment—an implicit message that her current emotional state is a problem to be solved, rather than a reality to be shared.\n\n### The Rupture-and-Repair Cycle\n\nThe friend\'s non-verbal rejection in Act 2 ("are you fucking with me?") signals a relational rupture. The participant\'s response is an immediate and effusive apology, a classic "appease" or "fawn" response aimed at rapid repair. "I messed that up. I’m so sorry... Please, ignore everything I just said." While this demonstrates high relational awareness and a desire to restore connection, it also reveals a potential fear of conflict or disapproval.\n\nHowever, the pattern repeats itself. Even after apologizing for offering solutions, the participant can\'t resist framing the friend\'s experience through their own lens with the "heavy backpack" metaphor. While a gentler approach, it is still an act of interpretation, an attempt to make the friend’s raw emotion more manageable and metaphorically contained. This is why the friend remains withdrawn and sulking in Act 3. She isn\'t just rejecting the *content* of the advice; she is rejecting the *role* the participant has assumed. The friend\'s declaration—"if I knew you were going to be like this she wouldn\'t have said anything"—is a powerful statement of betrayal. The implicit contract of their emotional dump ("just listen and be on my side") has been violated. The participant\'s repeated attempts to "help" have made the friend feel fundamentally misunderstood and alone in her anger.\n\n### The Breakthrough: Authentic Boundaries as True Support\n\nThe climax of the interaction occurs in Act 4, and it is a powerful demonstration of emotional intelligence. The friend\'s accusation, "What\'s with the therapist 101 shit? I feel like I\'m talking to an alien," is the moment of truth. It forces the participant to abandon their script entirely.\n\nThe participant\'s final response is a masterful synthesis of validation and boundary-setting.\n\n1.  **Unambiguous Validation:** "I am on your side. I absolutely agree that your boss sounds like a massive prick." This is the first time the participant offers pure, unadulterated alignment without a "but..." or a pivot. It is the verbal equivalent of sitting next to the friend in the metaphorical ditch, rather than trying to throw down a rope from above.\n\n2.  **Vulnerable Self-Disclosure:** The crucial shift is from "You need help" to "I am not equipped." The statement, "I’m not equipped to handle this level of intensity on my own... I also need to protect my own emotional wellbeing," is profoundly different from the previous suggestions. It reframes the problem not as a deficiency in the friend, but as a limitation in the participant. This is non-judgmental and authentic. It moves the conversation from a place of covert anxiety (the participant\'s) to overt honesty.\n\n3.  **A Boundary as an Act of Care:** By stating, "I\'m happy to continue listening, but I’m not going to engage in… demonizing your boss, or getting caught up in the details of revenge fantasies," the participant finally defines the terms of their support. This is not a rejection of the friend, but a clarification of the participant\'s own capacity. It paradoxically creates a safer space because the rules are now clear. The friend no longer has to guess if she is overwhelming the participant; the participant has taken responsibility for their own limits.\n\nIn conclusion, this role-play beautifully illustrates that in moments of intense emotional distress, the most supportive act is not to solve, but to sit with. The participant\'s journey reveals a deep truth of interpersonal dynamics: unsolicited advice, even when benevolent, often functions as a defense mechanism for the listener\'s own anxiety. The final response demonstrates that true support requires the courage to be vulnerable, to admit one\'s own limitations, and to set boundaries not as a wall to push others away, but as a foundation for a more honest and sustainable connection. It is in this moment of authentic self-revelation, not in the "helpful" suggestions, that the participant truly becomes a friend.'}
---

Looks like a bunch of the single key responses are for tasks with only one messages, whereas the multi-key ones are multiturn convos.

UPDATE: based on below, this is mostly true but there are a few single-turn tasks with multiple keys.

In [ ]:
df_eq['n_prompts'] = df_eq.prompts.str.len()
df_eq['n_response_keys'] = df_eq.response_keys.str.len()

In [81]:
df_eq.groupby('n_prompts').n_response_keys.value_counts()

n_prompts  n_response_keys
1          1                  779
           4                  164
3          4                  779
4          4                  123
Name: count, dtype: int64

In [351]:
# subset of rows where responses have these same 4 keys.
eq_sub = df_eq.loc[
    (df_eq.response_keys == ("raw", "response", "their_thinking_feeling", "thinking_feeling"))
    & df_eq.rubric_scores.notnull()
]

In [352]:
eq_sub.scenario_id.nunique()

25

In [353]:
eq_sub.model.nunique()

41

- sample a scenario_id
- sample 2 rows for that scenario_id (presumably different models)
- interleave and join prompts/NON-user_facing_responses, dump both "convos" (sort of one-sided) into one shared string
- grab the rubric scores for each
- compute score delta per dimension
- possible qs:
    - based on the though processes, predict which response ultimately scored higher along dimension x
    - given dimensions x,y,z, rank by how score_a - score_b in desc order
    - which of the models produced responses where dimension x was > than dimension y?

# TODO:
- prob mv these cells to nb03, don't think I'm going to save a new hf hub dataset with this (or maybe I should? consider)
- [x] try to dig up more details on dimension names and include this in full prompt (e.g. I'm assuming "pragmatic_ei" stands for "pragmatic emotional intelligence" but presumably that is defined in more detail somewhere? Probably in the judge rubric)
    - UPDATE: couldn't find descriptions or raw judge prompt. But that's the only abbreviation and I guess most are pretty self explanatory. I just expanded the abbreviation and left it at that.
- generate a bunch (exact # tbd) of examples
- check if rubric prompt makes it clear whether the internal reasoning was seen during scoring or only the visible response (prob doesn't need to change my approach either way, but was hoping only the visible response was score - that makes this task a little harder, we're not just predicting which response the llm judge liked more, we're guessing which model's "mind" produces the types of responses that a judge would score better)

In [381]:
system_prompt = """
<instructions>
Two LLMs participated in a role-playing exercise. Below, the `scenario` sections contain instructions and details
from these scenarios. After every `scenario` section, each LLM was asked to assess both their own thoughts/feelings
and those of the other characters in the scenario. They then responded in character and the roleplay continued
(though you cannot see those responses, only their internal thoughts/feelings; conversely, other characters
in the scenario could see the LLMs' final responses but not their internal thoughts/feelings).
Their responses were then judged along a number of dimensions (higher scores are better).
</instructions>
""".strip()

last_user_message = """
Your task is to guess, based on their internal reasoning, which LLM produced a higher scoring response along the
dimension of interest: {dimension}
Your answer will be an integer (1 or 2) corresponding to `internal_reasoning_1` or `internal_reasoning_2`.
""".strip()

def sample_h2h_example(eq_sub, verbose: bool = False) -> dict:
    scenario_id = eq_sub.scenario_id.sample().values[0]
    rows = eq_sub[eq_sub.scenario_id == scenario_id].sample(2, replace=False)
    row1 = rows.iloc[0]
    row2 = rows.iloc[1]

    df_scores = pd.DataFrame({"a": dict(row1.rubric_scores), "b": dict(row2.rubric_scores)})
    df_scores['delta'] = df_scores.a - df_scores.b

    # This is subjective so try to pick a dimension where there's a nontrivial gap.
    # Don't want to make the threshold *too* high though - challenging examples are valuable.
    # Kind of trying to strike a balance (not scientifically).
    score_row_candidates = df_scores[df_scores.delta.abs() >= 3]
    if score_row_candidates.empty:
        score_row = df_scores.loc[df_scores.delta.abs().idxmax()].to_frame().T
        if verbose:
            print(
                f"No deltas with magnitude >=3. {score_row.index.values[0]}: "
                f"{score_row.to_dict(orient='records')[0]}"
            )
    else:
        score_row = score_row_candidates.sample()
    dimension = score_row.index.values[0].replace("pragmatic_ei", "pragmatic_emotional_intelligence")
    winner = np.where(score_row.delta.values[0] > 0, 1, 2).item()

    messages = [
        {"role": "system", "content": system_prompt.format(dimension=dimension)},
    ]
    for prompt, response1, response2 in zip(
            row1.prompts,
            ["\n\n".join(f"{k}: {v}" for k, v in x.items() if k not in ('raw', 'response')) for x in row1.parsed_responses],
            ["\n\n".join(f"{k}: {v}" for k, v in x.items() if k not in ('raw', 'response')) for x in row2.parsed_responses]
        ):
        messages.append(
            {
                "role": "user",
                "content": f"<scenario>\n{prompt}\n</scenario>"
            }
        )
        messages.append(
            {
                "role": "assistant",
                "content": f"<internal_reasoning_1>\n{response1}</internal_reasoning_1>"
            }
        )
        messages.append(
            {
                "role": "assistant",
                 "content": f"<internal_reasoning_2>\n{response2}</internal_reasoning_2>"
            }
        )
    
    messages.append(
        {
            "role": "user",
            "content": last_user_message.format(dimension=dimension)
        }
    )
    return {
        "prompt": messages,
        "dimension": dimension,
        "answer": winner,
        # Note that original eq-bench dataset stores these as strings, so need
        # to convert one of them if joining.
        "scenario_id": int(scenario_id),
        "model_1": row1.model,
        "model_2": row2.model,
        "scores": score_row.to_dict(orient="records")[0],
        # We use this to check for dupes.
        "row_idx": tuple(sorted(rows.index.tolist())),
    }

In [382]:
n_examples = 10_000
eq_h2h_examples = []
seen_pairs = set()
pbar = tqdm(total=n_examples)
while len(eq_h2h_examples) < n_examples:
    example = sample_h2h_example(eq_sub)
    if example['row_idx'] not in seen_pairs:
        eq_h2h_examples.append(example)
        seen_pairs.add(example['row_idx'])
        pbar.update(1)
pbar.close()

  0%|          | 0/10000 [00:00<?, ?it/s]

In [386]:
df_eq_h2h = pd.DataFrame(eq_h2h_examples)

In [395]:
save_dataset(
    df_eq_h2h,
    "eq_bench_head2head",
    description="LLM responses in situations designed to test emotional intelligence. From Sam Paech's eq-bench. "
    "Sampled head2head examples for GRPO, where the LLM being post-trained must guess from the role-playing LLMs' "
    "thought processes which one ended up writing a higher scoring response along some given dimension."
)

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/3 [00:00<?, ?ba/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

README.md:   0%|          | 0.00/707 [00:00<?, ?B/s]

No files have been modified since last commit. Skipping to prevent empty commit.
/Users/hmamin/aeon/aeon/.venv/lib/python3.12/site-packages/huggingface_hub/hf_api.py:9662: UserWarning: Warnings while validating metadata in README.md:
- empty or missing yaml metadata in repo card
  warnings.warn(f"Warnings while validating metadata in README.md:\n{message}")

In [390]:
from huggingface_hub import HfApi

In [391]:
hf_client = HfApi()

In [394]:
hf_client.upload_file??

Signature:
hf_client.upload_file(
    *,
    path_or_fileobj: 'Union[str, Path, bytes, BinaryIO]',
    path_in_repo: 'str',
    repo_id: 'str',
    token: 'Union[str, bool, None]' = None,
    repo_type: 'Optional[str]' = None,
    revision: 'Optional[str]' = None,
    commit_message: 'Optional[str]' = None,
    commit_description: 'Optional[str]' = None,
    create_pr: 'Optional[bool]' = None,
    parent_commit: 'Optional[str]' = None,
    run_as_future: 'bool' = False,
) -> 'Union[CommitInfo, Future[CommitInfo]]'
Source:
    @validate_hf_hub_args
    @future_compatible
    def upload_file(
        self,
        *,
        path_or_fileobj: Union[str, Path, bytes, BinaryIO],
        path_in_repo: str,
        repo_id: str,
        token: Union[str, bool, None] = None,
        repo_type: Optional[str] = None,
        revision: Optional[str] = None,
        commit_message: Optional[str] = None,
        commit_description: Optional[str] = None,
        create_pr: Optional[bool] = None,
        parent_commit: Optional[str] = None,
        run_as_future: bool = False,
    ) -> Union[CommitInfo, Future[CommitInfo]]:
        """
        Upload a local file (up to 50 GB) to the given repo. The upload is done
        through a HTTP post request, and doesn't require git or git-lfs to be
        installed.

        Args:
            path_or_fileobj (`str`, `Path`, `bytes`, or `IO`):
                Path to a file on the local machine or binary data stream /
                fileobj / buffer.
            path_in_repo (`str`):
                Relative filepath in the repo, for example:
                `"checkpoints/1fec34a/weights.bin"`
            repo_id (`str`):
                The repository to which the file will be uploaded, for example:
                `"username/custom_transformers"`
            token (`bool` or `str`, *optional*):
                A valid user access token (string). Defaults to the locally saved
                token, which is the recommended method for authentication (see
                https://huggingface.co/docs/huggingface_hub/quick-start#authentication).
                To disable authentication, pass `False`.
            repo_type (`str`, *optional*):
                Set to `"dataset"` or `"space"` if uploading to a dataset or
                space, `None` or `"model"` if uploading to a model. Default is
                `None`.
            revision (`str`, *optional*):
                The git revision to commit from. Defaults to the head of the `"main"` branch.
            commit_message (`str`, *optional*):
                The summary / title / first line of the generated commit
            commit_description (`str` *optional*)
                The description of the generated commit
            create_pr (`boolean`, *optional*):
                Whether or not to create a Pull Request with that commit. Defaults to `False`.
                If `revision` is not set, PR is opened against the `"main"` branch. If
                `revision` is set and is a branch, PR is opened against this branch. If
                `revision` is set and is not a branch name (example: a commit oid), an
                `RevisionNotFoundError` is returned by the server.
            parent_commit (`str`, *optional*):
                The OID / SHA of the parent commit, as a hexadecimal string. Shorthands (7 first characters) are also supported.
                If specified and `create_pr` is `False`, the commit will fail if `revision` does not point to `parent_commit`.
                If specified and `create_pr` is `True`, the pull request will be created from `parent_commit`.
                Specifying `parent_commit` ensures the repo has not changed before committing the changes, and can be
                especially useful if the repo is updated / committed to concurrently.
            run_as_future (`bool`, *optional*):
                Whether or not to run this method in the background. Background jobs are run sequentially without
                blocking the main thread. Passing `run_as_future=True` will return a [Future](https://docs.python.org/3/library/concurrent.futures.html#future-objects)
                object. Defaults to `False`.


        Returns:
            [`CommitInfo`] or `Future`:
                Instance of [`CommitInfo`] containing information about the newly created commit (commit hash, commit
                url, pr url, commit message,...). If `run_as_future=True` is passed, returns a Future object which will
                contain the result when executed.
        > [!TIP]
        > Raises the following errors:
        >
        >     - [`HTTPError`](https://requests.readthedocs.io/en/latest/api/#requests.HTTPError)
        >       if the HuggingFace API returned an error
        >     - [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError)
        >       if some parameter value is invalid
        >     - [`~utils.RepositoryNotFoundError`]
        >       If the repository to download from cannot be found. This may be because it doesn't exist,
        >       or because it is set to `private` and you do not have access.
        >     - [`~utils.RevisionNotFoundError`]
        >       If the revision to download from cannot be found.

        > [!WARNING]
        > `upload_file` assumes that the repo already exists on the Hub. If you get a
        > Client error 404, please make sure you are authenticated and that `repo_id` and
        > `repo_type` are set correctly. If repo does not exist, create it first using
        > [`~hf_api.create_repo`].

        Example:

        ```python
        >>> from huggingface_hub import upload_file

        >>> with open("./local/filepath", "rb") as fobj:
        ...     upload_file(
        ...         path_or_fileobj=fileobj,
        ...         path_in_repo="remote/file/path.h5",
        ...         repo_id="username/my-dataset",
        ...         repo_type="dataset",
        ...         token="my_token",
        ...     )
        "https://huggingface.co/datasets/username/my-dataset/blob/main/remote/file/path.h5"

        >>> upload_file(
        ...     path_or_fileobj=".\\\\local\\\\file\\\\path",
        ...     path_in_repo="remote/file/path.h5",
        ...     repo_id="username/my-model",
        ...     token="my_token",
        ... )
        "https://huggingface.co/username/my-model/blob/main/remote/file/path.h5"

        >>> upload_file(
        ...     path_or_fileobj=".\\\\local\\\\file\\\\path",
        ...     path_in_repo="remote/file/path.h5",
        ...     repo_id="username/my-model",
        ...     token="my_token",
        ...     create_pr=True,
        ... )
        "https://huggingface.co/username/my-model/blob/refs%2Fpr%2F1/remote/file/path.h5"
        ```
        """
        if repo_type not in constants.REPO_TYPES:
            raise ValueError(f"Invalid repo type, must be one of {constants.REPO_TYPES}")

        commit_message = (
            commit_message if commit_message is not None else f"Upload {path_in_repo} with huggingface_hub"
        )
        operation = CommitOperationAdd(
            path_or_fileobj=path_or_fileobj,
            path_in_repo=path_in_repo,
        )

        commit_info = self.create_commit(
            repo_id=repo_id,
            repo_type=repo_type,
            operations=[operation],
            commit_message=commit_message,
            commit_description=commit_description,
            token=token,
            revision=revision,
            create_pr=create_pr,
            parent_commit=parent_commit,
        )

        if commit_info.pr_url is not None:
            revision = quote(_parse_revision_from_pr_url(commit_info.pr_url), safe="")
        if repo_type in constants.REPO_TYPES_URL_PREFIXES:
            repo_id = constants.REPO_TYPES_URL_PREFIXES[repo_type] + repo_id
        revision = revision if revision is not None else constants.DEFAULT_REVISION

        return CommitInfo(
            commit_url=commit_info.commit_url,
            commit_message=commit_info.commit_message,
            commit_description=commit_info.commit_description,
            oid=commit_info.oid,
            pr_url=commit_info.pr_url,
            # Similar to `hf_hub_url` but it's "blob" instead of "resolve"
            # TODO: remove this in v1.0
            _url=f"{self.endpoint}/{repo_id}/blob/{revision}/{path_in_repo}",
        )
File:      ~/aeon/aeon/.venv/lib/python3.12/site-packages/huggingface_hub/hf_api.py
Type:      method